rectorphp/rector-symfony

config/sets/swiftmailer/swiftmailer-to-symfony-mailer.php, src/Rector/ClassMethod/TemplateAnnotationToThisRenderRector.php, src/Rector/MethodCall/SwiftCreateMessageToNewEmailRector.php, src/Set/SwiftmailerSetList.php, src/TypeDeclaration/ReturnTypeDeclarationUpdater.php, stubs/SwiftMailer/Swift_Mailer.php, tests/Rector/MethodCall/SwiftCreateMessageToNewEmailRector/Fixture/fixture.php.inc, tests/Rector/MethodCall/SwiftCreateMessageToNewEmailRector/Fixture/skip_non_swift_mailer_create_message.php.inc, tests/Rector/MethodCall/SwiftCreateMessageToNewEmailRector/SwiftCreateMessageToNewEmailRectorTest.php, tests/Rector/MethodCall/SwiftCreateMessageToNewEmailRector/config/configured_rule.php
refs https://github.com/rectorphp/rector/issues/6654
This is just the beginning of the migration and a few more things need to be done like replacing
```php
$this->swift->setSender($address, $name);
```
with
```php
is_array($address)
? $this->email->sender(...$address)
: $this->email->sender(new Address($address, (string) $name));
```
etc. but I figured this might be too big for one PR and should therefore be split up into more PRs.
I'm also not sure about the SetList (if we should already "release it" while it isn't complete yet)
=> Migration: SwiftMailer to Symfony/Mailer

src/Rector/ClassMethod/TemplateAnnotationToThisRenderRector.php
Based on https://github.com/rectorphp/rector-src/pull/812 as this direct call is deprecated.
=> [Symfony] Using NodesToAddCollector on call addNodesAfterNode()

src/Bridge/NodeAnalyzer/ControllerMethodAnalyzer.php
Like in https://github.com/rectorphp/rector-src/pull/1120#issue-1041017838
=> [Symfony] Avoid error Argument #1 ($scope) must be of type PHPStan\Analyser\Scope, null given

src/NodeAnalyzer/DependencyInjectionMethodCallAnalyzer.php, tests/Rector/MethodCall/ContainerGetToConstructorInjectionRector/Fixture/skip_trait.php.inc
Currently rector fails hardly when trying to analyze my Create Traits which I use in tests and access dependency over `getContainer` method of the KernelTestCase. As following the books advice we should always ignore instead of fail.
fixes #53
=> Should ignore DependencyInjectionMethodCallAnalyzer when used inside traits

src/Rector/MethodCall/ContainerGetToConstructorInjectionRector.php, stubs/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php, tests/Rector/MethodCall/ContainerGetToConstructorInjectionRector/Fixture/skip_test_case.php.inc, tests/Rector/MethodCall/ContainerGetToConstructorInjectionRector/Fixture/skip_test_case_static_call.php.inc
Closes https://github.com/rectorphp/rector-symfony/pull/65
Closes https://github.com/rectorphp/rector-symfony/issues/64
=> Avoid ContainerGetToConstructorInjectionRector on TestCase classes

src/Rector/New_/StringToArrayArgumentProcessRector.php, tests/Rector/New_/StringToArrayArgumentProcessRector/Fixture/do_not_convert_to_array_after_instantiation.php.inc
Relates to #67 and #70
I went through to check that #70 covered all the cases and it looks like at least 2 methods are missed with this approach. I have added those methods here.
=> Overzealous string to array conversion

composer.json
@TomasVotruba Looking at other rector packages, eg:
https://github.com/rectorphp/rector-nette/commit/1e3b3ab4e1248623b020ce9c8e744ad89e942e74
The `danielstjules/stringy` was removed, I think it should be removed as well.
=> [Dep] Remove stringy as replaced with symfony/string

config/sets/symfony/level/up-to-symfony-53.php, config/sets/symfony/level/up-to-symfony-60.php, config/sets/symfony/symfony53.php, config/sets/symfony/symfony54.php, config/sets/symfony/symfony6/symfony-return-types.php, config/sets/symfony/symfony60.php, src/Set/SymfonySetList.php
Ref https://github.com/rectorphp/rector-symfony/issues/81
=> Extend Symfony 5.3, 5.4 and 6.0 sets

src/NodeAnalyzer/DependencyInjectionMethodCallAnalyzer.php, tests/Rector/MethodCall/ContainerGetToConstructorInjectionRector/Fixture/some_translator_exists3.php.inc
Continue of https://github.com/rectorphp/rector-symfony/pull/117, given the following code cause infinite loop:
```php
final class SomeTranslatorExists3 extends AbstractController
{
private SomeTranslator $someTranslator;
private SomeTranslator $someTranslator2;
public function __construct(SomeTranslator $someTranslator, SomeTranslator $someTranslator2)
{
$this->someTranslator = $someTranslator;
$this->someTranslator2 = $someTranslator2;
}
protected function execute()
{
$someService = $this->getContainer()->get('translator');
$someService = $this->getContainer()->get('translator')->translateSomething();
}
}
```
This PR fix it.
=> fix infinite loop on ContainerGetToConstructorInjectionRector

src/NodeAnalyzer/DependencyInjectionMethodCallAnalyzer.php, tests/Rector/MethodCall/ContainerGetToConstructorInjectionRector/Fixture/some_translator_different_object.php.inc, tests/Rector/MethodCall/ContainerGetToConstructorInjectionRector/Fixture/some_translator_exists.php.inc, tests/Rector/MethodCall/ContainerGetToConstructorInjectionRector/Fixture/some_translator_exists3.php.inc, tests/Rector/MethodCall/ContainerGetToConstructorInjectionRector/Fixture/some_translator_exists_different_name.php.inc, tests/Rector/MethodCall/ContainerGetToConstructorInjectionRector/Source/SomeTanslator.php
Make `ContainerGetToConstructorInjectionRector` only increment naming for new property when name is equal but different object, use existing when exists.
=> [Symfony] Only Increment property name when different object on ContainerGetToConstructorInjectionRector

config/sets/symfony/symfony52-validator-attributes.php
Support for all theses attributes was added in Symfony 5.2, together with the already present Groups attribute
see https://github.com/symfony/symfony/pull/38525
there is only one missing Serializer annotation, but it was added in Symfony 5.4, so I left that one out
https://github.com/symfony/symfony/pull/38525
=> Add missing annotations to symfony52-validator-attributes set

config/sets/symfony/symfony42.php
Upstream projected reverted the backward-compatibility breaking change.
Fixes #160.
=> Remove obsolete ArgumentAdder

composer.json, config/config.php, phpstan.neon, src/Command/RectorRoutesExportCommand.php, src/DataProvider/RouteMapProvider.php, src/Exception/JsonRoutesNotExistsException.php, src/Rector/ClassMethod/AddRouteAnnotationRector.php, src/ValueObject/RouteMap/RouteMap.php, src/ValueObject/SymfonyRouteMetadata.php, src/ValueObjectFactory/RouteMapFactory.php, tests/Rector/ClassMethod/AddRouteAnnotationRector/AddRouteAnnotationRectorTest.php, tests/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture.php.inc, tests/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture_missing_route.php.inc, tests/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture_with_existing_annotation.php.inc, tests/Rector/ClassMethod/AddRouteAnnotationRector/config/configured_rule.php, tests/Rector/ClassMethod/AddRouteAnnotationRector/config/route.json
See https://github.com/rectorphp/rector-symfony/issues/168
=> Add new rule to add annotations from router configuration to symfony controllers

config/sets/symfony/symfony30.php, src/NodeFactory/FormType/BuildFormOptionAssignsFactory.php, src/NodeRemover/ConstructorDependencyRemover.php, src/Rector/Class_/FormTypeWithDependencyToOptionsRector.php, tests/Rector/Class_/FormTypeWithDependencyToOptionsRector/Fixture/rename_only_local_properties.php.inc, tests/Rector/Class_/FormTypeWithDependencyToOptionsRector/Fixture/skip_no_ctor_params.php.inc, tests/Rector/Class_/FormTypeWithDependencyToOptionsRector/Fixture/some_class.php.inc, tests/Rector/Class_/FormTypeWithDependencyToOptionsRector/FormTypeWithDependencyToOptionsRectorTest.php
- [Symfony 2.8] Add FormTypeWithDependencyToOptionsRector
- skip no params used
=> [Symfony 2.8] Add FormTypeWithDependencyToOptionsRector

src/NodeAnalyzer/Annotations/MethodCallAnnotationAssertResolver.php, src/Rector/Class_/MagicClosureTwigExtensionToNativeMethodsRector.php, src/ValueObject/SymfonyRouteMetadata.php, tests/Rector/ClassMethod/AddRouteAnnotationRector/config/routes.json
Today I've found a new edge case which occurs a error in the `AddRouteAnnotationRector` rule.
If you define a route with a path but without a controller (it's allowed in Symfony) the `Rector\Symfony\ValueObject\SymfonyRouteMetadata::getControllerReference()` method throws the error `Return value must be of type string, null returned`.
=> Bugfix: Allow nullable for ControllerReference (AddRouteAnnotationRector)

src/Rector/New_/StringToArrayArgumentProcessRector.php, tests/Rector/New_/StringToArrayArgumentProcessRector/Fixture/skip_sprintf_no_space.php.inc
Given the following code:
```php
use Symfony\Component\Process\Process;
$command = sprintf("FOO=%s", 10);
$process = new Process($command);
```
it currently produce:
```diff
-$command = sprintf("FOO=%s", 10);
+$command = ['FOO=%s'];
```
which should be skipped.
Fixes https://github.com/rectorphp/rector-symfony/issues/188
=> [Symfony] Skip sprintf no space on StringToArrayArgumentProcessRector

src/NodeFactory/Annotations/ValueQuoteWrapper.php, src/Rector/ClassMethod/AddRouteAnnotationRector.php, tests/NodeFactory/Annotations/ValueQuoteWrapperTest.php, tests/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture.php.inc, tests/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture_missing_route.php.inc
New day, new bug, new fix 🙃
I've got a semantical error because of the unquoted keys of the `defaults` and `requirements` parameters.
```
[Semantical Error] Couldn't find constant company, method Foo\BarBundle\Controller\FooController::deleteFooAction() in /var/www/config/routes/../../src/Foo/BarBundle/Controller/ (which is being imported from "/var/www/config/routes/annotations.yaml"). Make sure annotations are installed and enabled.
```
---
FYI: I finally have time to use the AddRouteAnnotationRector rule on the project for which I needed the rule 🎉  I've also seen that the `options` of a route are missing but I will add them in a separate PR.
=> Bugfix: Wrap array keys with quotes to prevent a semantical error (AddRouteAnnotationRector)

config/sets/symfony/symfony52.php
per @MartinMystikJonas comment on https://github.com/rectorphp/rector-src/pull/2653#issuecomment-1180208203 with merge to single service registration for `RenameMethodRector`.
=> Fix merge config on symfony52 config set

tests/Rector/MethodCall/FormBuilderSetDataMapperRector/Fixture/form_trait_data_mapper.php.inc
Same as https://github.com/rectorphp/rector-symfony/pull/185
Based on https://getrector.org/demo/ef71e26f-5722-4f99-a450-4d19a119eb61
=> [FormBuilderSetDataMapperRector] Invalid data mapper replacement

config/sets/symfony/level/up-to-symfony-27.php, config/sets/symfony/symfony27.php, config/sets/symfony/symfony30.php, src/Set/SymfonyLevelSetList.php, src/Set/SymfonySetList.php
Fixes https://github.com/rectorphp/rector-symfony/issues/214
=> [Symfony 2.7] Move ChangeCollectionTypeOptionNameFromTypeToEntryTypeRector to symfony 2.7 config set

src/Rector/Class_/InvokableControllerRector.php, src/Rector/New_/RootNodeTreeBuilderRector.php, tests/Rector/Class_/InvokableControllerRector/Fixture/single_action_with_construct.php.inc
Given the following code:
```php
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Serializer\SerializerInterface;
final class SingleActionWithConstruct extends AbstractController
{
public function __construct(
private SerializerInterface $serializer,
) {
}
public function create(): Response
{
return $this->json([], Response::HTTP_CREATED);
}
}
```
It currently produce error:
```bash
There was 1 error:
1) Rector\Symfony\Tests\Rector\Class_\InvokableControllerRector\InvokableControllerRectorTest::test with data set #1 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Undefined array key 0
```
Fixes https://github.com/rectorphp/rector/issues/7365
=> [Symfony] Handle single action with __construct on InvokableControllerRector

phpstan.neon, src/Rector/ClassMethod/RemoveDefaultGetBlockPrefixRector.php, tests/Rector/ClassMethod/RemoveDefaultGetBlockPrefixRector/Fixture/skip_extending_custom_type.php.inc, tests/Rector/ClassMethod/RemoveDefaultGetBlockPrefixRector/Fixture/skip_no_parent.php.inc, tests/Rector/ClassMethod/RemoveDefaultGetBlockPrefixRector/Fixture/skip_with_get_block_prefix.php.inc, tests/Rector/ClassMethod/RemoveDefaultGetBlockPrefixRector/Source/CustomType.php
Fixes https://github.com/rectorphp/rector/issues/7347
Closes https://github.com/rectorphp/rector-symfony/pull/212
=> Skip non-direct inheritors for AbstractType in RemoveDefaultGetBlockPrefixRector

src/Rector/MethodCall/WebTestCaseAssertResponseCodeRector.php, tests/Rector/MethodCall/WebTestCaseAssertResponseCodeRector/Fixture/handle_static_calls.php.inc
Both PHPUnit's and Symfony's `assert*` methods are `static`, so this adds the handling of static calls.
=> Handle static calls in WebTestCaseAssertResponseCodeRector

config/sets/symfony/symfony53.php, config/sets/symfony/symfony60.php, src/NodeAnalyzer/SymfonyTestCaseAnalyzer.php, src/Rector/StaticPropertyFetch/KernelTestCaseContainerPropertyDeprecationRector.php, tests/Rector/StaticPropertyFetch/KernelTestCaseContainerPropertyDeprecationRector/Fixture/change_to_method_call.php.inc, tests/Rector/StaticPropertyFetch/KernelTestCaseContainerPropertyDeprecationRector/Fixture/skip_access_in_another_class.php.inc, tests/Rector/StaticPropertyFetch/KernelTestCaseContainerPropertyDeprecationRector/Fixture/skip_other_classes.php.inc, tests/Rector/StaticPropertyFetch/KernelTestCaseContainerPropertyDeprecationRector/KernelTestCaseContainerPropertyDeprecationRectorTest.php, tests/Rector/StaticPropertyFetch/KernelTestCaseContainerPropertyDeprecationRector/config/configured_rule.php
Symfony deprecated `KernelTestCase::$container` back in `5.3` (https://github.com/symfony/symfony/blob/5.3/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php#L39) and removed it in `6.0`.
The recommended alternative ist to call `KernelTestCase::getContainer()` instead.
=> Add rector to replace KernelTestCase::$container with KernelTestCase::getContainer() in tests

rector.php
ref https://github.com/rectorphp/rector-symfony/pull/235#pullrequestreview-1094097162
I think the skip config should actually merge instead of replace existing `classesToSkip` config.
=> Exclude Error and Exception class name on StringClassNameToClassConstantRector

src/Rector/ClassMethod/ConsoleExecuteReturnIntRector.php, tests/Rector/ClassMethod/ConsoleExecuteReturnIntRector/Fixture/skip_try_catch_return.php.inc
Closes https://github.com/rectorphp/rector-symfony/pull/238
=> [Symfony] Skip Try Catch Return on ConsoleExecuteReturnIntRector

config/sets/sensiolabs/annotations-to-attributes.php, src/Set/SensiolabsSetList.php, tests/Set/SensiolabsAnnotationsToAttributes/Fixture/cache_fixture.php.inc, tests/Set/SensiolabsAnnotationsToAttributes/Fixture/entity_fixture.php.inc, tests/Set/SensiolabsAnnotationsToAttributes/Fixture/param_converter_fixture.php.inc, tests/Set/SensiolabsAnnotationsToAttributes/Fixture/security_and_is_granted_fixture.php.inc, tests/Set/SensiolabsAnnotationsToAttributes/Fixture/template_fixture.php.inc, tests/Set/SensiolabsAnnotationsToAttributes/SensiolabsAnnotationsToAttributesTest.php, tests/Set/SensiolabsAnnotationsToAttributes/config/sensiolabsAnnotationsToAttributes.php
SensioFrameworkExtraBundle support [attributes](https://symfony.com/bundles/SensioFrameworkExtraBundle/current/index.html#annotations-for-controllers). 
Added rules,  tests and link when this was [added](https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/707).
=> [Set] SensioLabs annotation to attribute

config/sets/symfony/symfony25.php, docs/rector_rules_overview.md, src/Rector/MethodCall/MaxLengthSymfonyFormOptionToAttrRector.php, stubs/Symfony/Component/Form/FormBuilder.php, stubs/Symfony/Component/Form/FormFactory.php, stubs/Symfony/Component/Form/FormFactoryInterface.php, tests/Rector/Array_/MaxLengthSymfonyFormOptionToAttrRector/Fixture/some_class.php.inc, tests/Rector/Array_/MaxLengthSymfonyFormOptionToAttrRector/Fixture/some_form_factory.php.inc, tests/Rector/Array_/MaxLengthSymfonyFormOptionToAttrRector/MaxLengthSymfonyFormOptionToAttrRectorTest.php, tests/Rector/Array_/MaxLengthSymfonyFormOptionToAttrRector/config/configured_rule.php
Ref:
* https://github.com/symfony/symfony-docs/pull/3461
* https://github.com/symfony/symfony/issues/7148
=> Add MaxLengthSymfonyFormOptionToAttrRector

src/Rector/ClassMethod/AddRouteAnnotationRector.php, tests/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture.php.inc, tests/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture_missing_route.php.inc, tests/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture_with_null_as_default.php.inc, tests/Rector/ClassMethod/AddRouteAnnotationRector/config/routes.json
* Fix issue that a `null` default parameter was a empty string as annotation
* Fix issue that boolean default parameter was a numeric string as annotation
* Fix issue that host was not quoted
https://github.com/rectorphp/rector-symfony/issues/242
=> AddRouteAnnotationRector: Some bugfixes

docs/rector_rules_overview.md, src/Rector/ClassMethod/RemoveUnusedRequestParamRector.php
@TomasVotruba yesterday I saw we where missing one more rule in the docs. After this it should be complete as the number of rules are same in rector folder and in docs.
I also changed code sample to show the correct output off the rule
=> [RemoveUnusedRequestParamRector] Add rector rule to docs

src/Rector/ClassMethod/MergeMethodAnnotationToRouteAnnotationRector.php, tests/Rector/ClassMethod/MergeMethodAnnotationToRouteAnnotationRector/Fixture/fixture.php.inc, tests/Rector/ClassMethod/MergeMethodAnnotationToRouteAnnotationRector/Fixture/fixture_with_single_method.php.inc
While upgrade a legacy project I noticed some `@Method` annotations were left out because the value was a single string.
This update adds support for single methods :)
=> [MergeMethodAnnotationToRouteAnnotationRector] Adding single method handling

src/Rector/MethodCall/WebTestCaseAssertResponseCodeRector.php
Fixes https://github.com/rectorphp/rector/issues/7540 after the fixture in https://github.com/rectorphp/rector-symfony/pull/267 has been corrected
=> [WebTestCaseAssertResponseCodeRector] Removing check for null value

src/Rector/ClassMethod/AddRouteAnnotationRector.php, tests/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture_duplicate.php.inc, tests/Rector/ClassMethod/AddRouteAnnotationRector/config/routes.json
I noticed that only the first "controller" match is migrated for "@Route" annotation. 
So given the pattern (eg "optional placeholder"), will be now also migrated with 2 annotations:
```
YYY:
path: /unit/{foo}.json
defaults:
_controller: XXX::yyyAction
XXX:
path: /unit/{foo}/{date}.json
defaults:
_controller: XXX::yyyAction
```
=> AddRouteAnnotationRector: add support for multiple controller matching

src/Rector/ClassMethod/AddRouteAnnotationRector.php, tests/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture.php.inc, tests/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture_missing_route.php.inc, tests/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture_with_null_as_default.php.inc
Route Migration Pfad: `xml/yaml > Annotation -> Attributes`
Currently PhpStorm reports wrong ordering of named arguments, maybe it would be nice to directly generate them ordered.
=> WIP: AddRouteAnnotationRector: respect ordering of named arguments on migration

config/sets/fosrest/annotations-to-attributes.php, src/Set/FOSRestSetList.php, tests/Set/FOSRestAnnotationsToAttributes/FOSRestAnnotationsToAttributesTest.php, tests/Set/FOSRestAnnotationsToAttributes/Fixture/param_fixture.php.inc, tests/Set/FOSRestAnnotationsToAttributes/Fixture/route_fixture.php.inc, tests/Set/FOSRestAnnotationsToAttributes/config/fosrestAnnotationsToAttributes.php
Added rules, tests and link when this was added [1](https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2327) [2](https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2326) [3](https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2325)
[Issue](https://github.com/rectorphp/rector-symfony/issues/241)
=> [Set] FOSRest annotation to attribute

phpstan.neon, src/Rector/New_/StringToArrayArgumentProcessRector.php
Fix PHPStan notice:
```
composer phpstan
> vendor/bin/phpstan analyse --ansi --error-format symplify
! [NOTE] The Xdebug PHP extension is active, but "--xdebug" is not used. This may  
!        slow down performance and the process will not halt at breakpoints.       
Note: Using configuration file /Users/samsonasik/www/rector-symfony/phpstan.neon.
394/394 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
[WARNING] Ignored error pattern #Parameter \#1 \$class of method                   
Rector\\BetterPhpDocParser\\PhpDocInfo\\PhpDocInfo<PHPStan\\PhpDocParser\</>
Ast\\Node>\:\:(.*?)\(\) expects class\-string, string given# was not     
matched in reported errors.                  
```
=> [PHPStan] Fix PHPStan notice

config/sets/symfony/symfony30.php
HI @TomasVotruba
According to
https://github.com/symfony/symfony/blob/3.4/UPGRADE-3.0.md#translator
```
The getMessages() method of the Symfony\Component\Translation\Translator class was removed. You should use the getCatalogue() method of the Symfony\Component\Translation\TranslatorBagInterface.
```
But the `Symfony\Component\Translation\Translator` class was not deprecated.
- We should still be able to use it as a param
- We should still be able to use it as a return type
- We should still be able to use it in the phpdoc
Currently some code like
```
/**
* @var Translator
*/
private Translator $translator;
/**
* @return Translator
*/
final protected function getTranslator(): Translator
{
return $this->translator;
}
```
is changed to
```
/**
* @var TranslatorBagInterface
*/
private …
```
=> Remove translator class renaming from Symfony 3.0

src/Rector/ClassMethod/CommandConstantReturnCodeRector.php, src/Rector/ClassMethod/ConsoleExecuteReturnIntRector.php, tests/Rector/ClassMethod/CommandConstantReturnCodeRector/Fixture/replace_fail.php.inc, tests/Rector/ClassMethod/CommandConstantReturnCodeRector/Fixture/replace_invalid.php.inc, tests/Rector/ClassMethod/CommandConstantReturnCodeRector/Fixture/replace_with_constant.php.inc
There is two issues, reported by 
Closes https://github.com/rectorphp/rector-symfony/issues/295
Closes https://github.com/rectorphp/rector-symfony/issues/293
The CommandConstantReturnCodeRector is changing `0` to `Command::Success`, even if `Command` is not imported.
This is breaking the code
Then ConsoleExecuteReturnIntRector is adding `(int)` before `Command::Success` before when resolving with phpstan the constant, an ErrorType is found.
This PR fix both of the issues.
=> Fix issues with ConsoleExecuteReturnIntRector and CommandConstantReturnCodeRector

tests/Rector/MethodCall/GetParameterToConstructorInjectionRector/Fixture/two_params_with_parent_constructor.php.inc
The expected behavior would be that the parent constructor is only called once.
=> Add failing test for GetParameterToConstructorInjectionRector

config/sets/symfony/symfony53.php, config/sets/symfony/symfony6/symfony-return-types.php, config/sets/symfony/symfony60.php, src/NodeFactory/Annotations/StringValueQuoteWrapper.php, src/Rector/ClassMethod/ConsoleExecuteReturnIntRector.php, src/Rector/ClassMethod/TemplateAnnotationToThisRenderRector.php, tests/Rector/ClassMethod/ConsoleExecuteReturnIntRector/Fixture/skip_remove_comment_deep_if.php.inc
Based on https://getrector.org/demo/b6b66790-9939-49ba-ba4a-0f6bd3496e49, the comment should not be removed on deep ifs.
Fixes https://github.com/rectorphp/rector/issues/7668
=> [Symfony] Skip remove comment deep statement on ConsoleExecuteReturnIntRector

README.md
Thanks for this impressive tool!
Sync with what is currently generated by Symfony 6. Alos fix the environment name (`test` by default, without the final `s`).
=> docs: modernize how to get Symfony containers

src/Rector/MethodCall/RedirectToRouteRector.php, tests/Rector/MethodCall/RedirectToRouteRector/Fixture/generate_url_with_default.php.inc, tests/Rector/MethodCall/RedirectToRouteRector/Fixture/generate_url_with_relative.php.inc
When the code passes a non-default `$referenceType` to the `generateUrl()` call the RedirectToRouteRector should not change the type of the resulting URL. That would be a breaking change.
The PR takes into account the default value defined in the user's UrlGeneratorInterface. But that's also the part I'm not so sure about - couldn't find a similar example in the existing code in reasonable time.
First time digging into the code of the tool, so any suggestions to improve are welcome.
=> [Symfony26] Fix RedirectToRouteRector with non-default reference type

config/sets/symfony/symfony62.php, docs/rector_rules_overview.md, src/Rector/ClassMethod/ParamConverterAttributeToMapEntityAttributeRector.php, tests/Rector/ClassMethod/ParamConverterAttributeToMapEntityAttributeRector/Fixture/multiple_paramconverters.php.inc, tests/Rector/ClassMethod/ParamConverterAttributeToMapEntityAttributeRector/Fixture/replace_paramconverter.php.inc, tests/Rector/ClassMethod/ParamConverterAttributeToMapEntityAttributeRector/Fixture/replace_paramconverter_more_options.php.inc, tests/Rector/ClassMethod/ParamConverterAttributeToMapEntityAttributeRector/Fixture/skip_datetimeconverter.php.inc, tests/Rector/ClassMethod/ParamConverterAttributeToMapEntityAttributeRector/ParamConverterAttributeToMapEntityAttributeRectorTest.php, tests/Rector/ClassMethod/ParamConverterAttributeToMapEntityAttributeRector/config/configured_rule.php
See https://github.com/rectorphp/rector-symfony/issues/264
This is my first time working with Rector and the AST so please add feedback 🙂 
Right now I'm confused why the `use` is not being removed (I thought `RenamedClassesDataCollector` would take care of that) and why the `MapEntity` is placed on a new line instead of prepended to the parameter.
1. Should this also replace `Entity` attributes since that is a shortcut for using `expr`?
=> [SYMFONY62] Replace ParamConverter with MapEntity

src/Rector/MethodCall/RedirectToRouteRector.php, tests/Rector/MethodCall/RedirectToRouteRector/Fixture/skip_other_generator.php.inc
Closes #350
Only refactor when `$this->generateUrl()` is being used
=> Adding check for variable name

composer.json, phpstan.neon, src/Rector/Closure/MinimalSharedStringSolver.php, src/Rector/Closure/ServiceSettersToSettersAutodiscoveryRector.php
closes https://github.com/rectorphp/rector/issues/7832
=> Drop triun/longest-common-substring dependency

src/NodeFactory/OnSuccessLogoutClassMethodFactory.php, src/NodeFactory/ThisRenderFactory.php, src/Rector/ClassMethod/AddRouteAnnotationRector.php, src/Rector/ClassMethod/ConsoleExecuteReturnIntRector.php, src/Rector/ClassMethod/FormTypeGetParentRector.php, src/Rector/ClassMethod/TemplateAnnotationToThisRenderRector.php, src/Rector/Class_/CommandPropertyToAttributeRector.php, src/Rector/Class_/EventListenerToEventSubscriberRector.php, src/Rector/MethodCall/ChangeCollectionTypeOptionNameFromTypeToEntryTypeRector.php, src/Rector/MethodCall/ChangeStringCollectionOptionToConstantRector.php, src/Rector/MethodCall/FormIsValidRector.php, src/Rector/MethodCall/FormTypeInstanceToClassConstRector.php, src/Rector/MethodCall/OptionNameRector.php, src/Rector/MethodCall/WebTestCaseAssertIsSuccessfulRector.php, src/Rector/MethodCall/WebTestCaseAssertResponseCodeRector.php, src/Rector/MethodCall/WebTestCaseAssertSelectorTextContainsRector.php, src/Rector/New_/StringToArrayArgumentProcessRector.php, src/Rector/Return_/SimpleFunctionAndFilterRector.php, src/TypeAnalyzer/JMSDITypeResolver.php, src/ValueObjectFactory/ServiceMapFactory.php, tests/Rector/MethodCall/WebTestCaseAssertResponseCodeRector/Fixture/http_code.php.inc
Resolve argument variable $message correctly for WebTestCaseAssertResponseCodeRector, WebTestCaseAssertIsSuccessfulRector and WebTestCaseAssertSelectorTextContainsRector
Fixes: https://github.com/rectorphp/rector/issues/7844
=> [WebTestCaseAssertResponseCodeRector] resolve message param fixes #7844

config/sets/symfony/symfony43.php, docs/rector_rules_overview.md, src/Rector/MethodCall/GetCurrencyBundleMethodCallsToIntlRector.php, src/ValueObject/IntlBundleClassToNewClass.php, stubs/Symfony/Component/Intl/Intl.php, stubs/Symfony/Component/Intl/ResourceBundle/CurrencyBundleInterface.php, tests/Rector/MethodCall/GetCurrencyBundleMethodCallsToIntlRector/Fixture/some_class.php.inc, tests/Rector/MethodCall/GetCurrencyBundleMethodCallsToIntlRector/GetCurrencyBundleMethodCallsToIntlRectorTest.php, tests/Rector/MethodCall/GetCurrencyBundleMethodCallsToIntlRector/config/configured_rule.php
See
* https://symfony.com/blog/new-in-symfony-4-3-simpler-access-to-intl-data
* https://github.com/symfony/symfony/pull/28846
=> [Symfony 4.3] Add GetCurrencyBundleMethodCallsToIntlRector

src/NodeAnalyzer/FormAddMethodCallAnalyzer.php, src/NodeAnalyzer/LiteralCallLikeConstFetchReplacer.php, src/NodeFactory/OnSuccessLogoutClassMethodFactory.php, src/Rector/ClassMethod/ParamTypeFromRouteRequiredRegexRector.php, src/Rector/ClassMethod/RemoveUnusedRequestParamRector.php, src/Rector/MethodCall/FormBuilderSetDataMapperRector.php, tests/Rector/ClassMethod/RemoveUnusedRequestParamRector/Fixture/do_not_override_parent_abstract_class_method.php.inc
=> Skip RemoveUnusedRequestParamRector on override abstract method

config/sets/symfony/symfony26.php, rules-tests/Symfony26/Rector/MethodCall/RedirectToRouteRector/Fixture/fixture.php.inc, rules-tests/Symfony26/Rector/MethodCall/RedirectToRouteRector/Fixture/fixture2.php.inc, rules-tests/Symfony26/Rector/MethodCall/RedirectToRouteRector/Fixture/fixture3.php.inc, rules-tests/Symfony26/Rector/MethodCall/RedirectToRouteRector/Fixture/fixture4.php.inc, rules-tests/Symfony26/Rector/MethodCall/RedirectToRouteRector/Fixture/generate_url_with_default.php.inc, rules-tests/Symfony26/Rector/MethodCall/RedirectToRouteRector/Fixture/generate_url_with_relative.php.inc, rules-tests/Symfony26/Rector/MethodCall/RedirectToRouteRector/Fixture/skip_other_generator.php.inc, rules-tests/Symfony26/Rector/MethodCall/RedirectToRouteRector/RedirectToRouteRectorTest.php, rules-tests/Symfony26/Rector/MethodCall/RedirectToRouteRector/config/configured_rule.php, rules/Symfony26/Rector/MethodCall/RedirectToRouteRector.php, rules/Symfony27/Rector/MethodCall/ChangeCollectionTypeOptionNameFromTypeToEntryTypeRector.php
- fix test path
- Move RedirectToRouteRector into Symfony26 category
=> [DX] Move RedirectToRouteRector into Symfony26 category

config/sets/symfony/symfony34.php, config/sets/symfony/symfony61.php
to avoid error:
```
1s
Run bin/rector missing-in-set --ansi
We could not find there rules in configs
========================================
* vendor/rector/rector-symfony/config/sets/symfony/symfony34.php
* Rector\Symfony\Symfony34\Rector\ClassMethod\RemoveServiceFromSensioRouteRector
We could not find there rules in configs
========================================
* vendor/rector/rector-symfony/config/sets/symfony/symfony61.php
* Rector\Symfony\Symfony61\Rector\Class_\MagicClosureTwigExtensionToNativeMethodsRector
```
ref https://github.com/rectorphp/rector-src/actions/runs/5365010566/jobs/9733554418?pr=4337#step:5:11
=> Register RemoveServiceFromSensioRouteRector and MagicClosureTwigExtensionToNativeMethodsRector to config set

rules-tests/Symfony30/Rector/Class_/FormTypeWithDependencyToOptionsRector/config/configured_rule.php, rules-tests/Symfony53/Rector/MethodCall/SwiftCreateMessageToNewEmailRector/config/configured_rule.php, rules-tests/Twig134/Rector/Return_/SimpleFunctionAndFilterRector/config/configured_rule.php
To avoid error in rector-src tests
```
There were 9 errors:
1) Rector\Symfony\Tests\Symfony30\Rector\Class_\FormTypeWithDependencyToOptionsRector\FormTypeWithDependencyToOptionsRectorTest::test with data set #0
Symfony\Component\Config\Exception\LoaderLoadException: The file "/home/runner/work/rector-src/rector-src/rules-tests/Symfony30/Rector/Class_/FormTypeWithDependencyToOptionsRector/config/../../../../../config/config.php" does not exist in /home/runner/work/rector-src/rector-src/rules-tests/Symfony30/Rector/Class_/FormTypeWithDependencyToOptionsRector/config/../../../../../config/config.php (which is being imported from "/home/runner/work/rector-src/rector-src/rules-tests/Symfony30/Rector/Class_/FormTypeWithDependencyToOptionsRector/config/configured_rule.php").
```
=> Fix location config in tests

rules-tests/Symfony62/Rector/MethodCall/SimplifyFormRenderingRector/Fixture/do_not_replace_other_function_calls.php.inc, rules/Symfony62/Rector/MethodCall/SimplifyFormRenderingRector.php
The SimplifyFormRenderingRector was replacing calls to methods other than ->createView(), which is no longer required in Symfony 6.2, e.g. calls to ->getData().
These are not deprecated and there's no reason to remove them, and in fact the blanket rule of removing any method calls of FormInterface parameters of the container $this->render() function is too wide and could lead to breakage.
=> Fix SimplifyFormRenderingRector replacing calls other than createView()

rules-tests/Symfony30/Rector/ClassMethod/RemoveDefaultGetBlockPrefixRector/Fixture/contains_unicode_name.php.inc, rules/Symfony30/Rector/ClassMethod/RemoveDefaultGetBlockPrefixRector.php
Ref https://github.com/rectorphp/rector-symfony/pull/511#pullrequestreview-1585885491
=> [Symfony30] Handle contains unicode string on RemoveDefaultGetBlockPrefixRector

.github/workflows/code_analysis.yaml, .github/workflows/tests.yaml, config/sets/symfony/symfony6/symfony-return-types.php, rules/Symfony43/Rector/ClassMethod/EventDispatcherParentConstructRector.php, rules/Symfony62/Rector/ClassMethod/ClassMethod/ArgumentValueResolverToValueResolverRector.php
Current github actions/checkout v3 got error:
```
Download action repository 'actions/checkout@v3' (SHA:f43a0e5ff2bd294095638e18286ca9a3d1956744)
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_4ecd32f5-c361-435e-b74b-7171ccb18414/3c125ce6-395a-4023-acd8-39fc47eba947.tar.gz. return code: 2.
```
Ref https://github.com/rectorphp/rector-src/actions/runs/6074243601/job/16477779233#step:1:35
It reported at:
- https://github.com/actions/checkout/issues/1448
This PR try to update to github actions/checkout v4.
=> Update github actions/checkout from v3 to v4

rules-tests/Configs/Rector/ClassMethod/AddRouteAnnotationRector/config/configured_rule.php
@hildebro here should fix https://github.com/rectorphp/rector-symfony/issues/516
=> [Configs] Alias SymfonyRoutesProviderInterface into SymfonyRoutesProvider

rules-tests/Symfony43/Rector/StmtsAwareInterface/TwigBundleFilesystemLoaderToTwigRector/Fixture/skip_not_instanceof_filesystem_loader.php.inc, rules/Symfony43/Rector/StmtsAwareInterface/TwigBundleFilesystemLoaderToTwigRector.php
Fixes https://github.com/rectorphp/rector/issues/8189
=> [Symfony43] Skip not instanceof FilesystemLoader via dynamic new $class on TwigBundleFilesystemLoaderToTwigRector

README.md
@hildebro @TomasVotruba per https://github.com/rectorphp/rector-symfony/pull/518#pullrequestreview-1615443164 as `AddRouteAnnotationRector` not part of any `SetList`.
I updated the readme for usage of `AddRouteAnnotationRector` for configure service aliased.
=> Update Readme for usage of AddRouteAnnotationRector

rules/CodeQuality/Rector/BinaryOp/ResponseStatusCodeRector.php
counterpart of https://github.com/rectorphp/rector-src/pull/4951
=> ResponseStatusCodeRector: use NodeNameResolver->matchesStringName()

rules-tests/CodeQuality/Rector/ClassMethod/ActionSuffixRemoverRector/Fixture/skip_get_action.php.inc, rules/CodeQuality/Rector/ClassMethod/ActionSuffixRemoverRector.php
Fixes https://github.com/rectorphp/rector-symfony/issues/510
=> [CodeQuality] Skip getAction() on ActionSuffixRemoverRector

config/sets/symfony/symfony62.php, rules/Twig134/Rector/Return_/SimpleFunctionAndFilterRector.php, src/NodeFactory/OnLogoutClassMethodFactory.php, src/NodeFactory/OnSuccessLogoutClassMethodFactory.php
@jambonfarci @stefantalen @TomasVotruba here ensure change annotation to attribute before rename,
see https://getrector.com/demo/894cda53-f2a9-4216-b64a-7ba2247b0a73
Ref https://github.com/rectorphp/rector-symfony/issues/535#issuecomment-1783983383
For auto import, it require PR on rector-src on auto import enabled usage:
- https://github.com/rectorphp/rector-src/pull/5213
=> [Symfony 62] Ensure change Annotation to Attribute first before rename Annotation on IsGranted, Cache, Template

config/sets/swiftmailer/swiftmailer-to-symfony-mailer.php, config/sets/symfony/symfony53.php, src/Set/SwiftmailerSetList.php
I came across these rules while working on a project.
Since these rules are incomplete for their purpose (as mentioned in #401) , I feel like they should not come with a Symfony set.
=> Separating Swiftmailer to Symfony Mailer from Symfony 5.3 set

rules-tests/CodeQuality/Rector/MethodCall/AssertSameResponseCodeWithDebugContentsRector/Fixture/skip_not_response_object.php.inc, rules/CodeQuality/Rector/MethodCall/AssertSameResponseCodeWithDebugContentsRector.php
Fixes https://github.com/rectorphp/rector/issues/8304
=> [CodeQuality] Skip not from Symfony Response object on AssertSameResponseCodeWithDebugContentsRector

config/sets/symfony/symfony64.php, rules-tests/Symfony64/Rector/Class_/ChangeRouteAttributeFromAnnotationSubnamespaceRector/ChangeRouteAttributeFromAnnotationSubnamespaceRectorTest.php, rules-tests/Symfony64/Rector/Class_/ChangeRouteAttributeFromAnnotationSubnamespaceRector/Fixture/use-annotation-should-skip.php.inc, rules-tests/Symfony64/Rector/Class_/ChangeRouteAttributeFromAnnotationSubnamespaceRector/Fixture/use-attribute-with-annotation-import-on-class.php.inc, rules-tests/Symfony64/Rector/Class_/ChangeRouteAttributeFromAnnotationSubnamespaceRector/Fixture/use-attribute-with-annotation-import.php.inc, rules-tests/Symfony64/Rector/Class_/ChangeRouteAttributeFromAnnotationSubnamespaceRector/config/configured_rule.php, rules/Symfony64/Rector/Class_/ChangeRouteAttributeFromAnnotationSubnamespaceRector.php
Integrate in Symfony upgrade the replacement of Symfony\Component\Routing\Annotation\Route by Symfony\Component\Routing\Attribute\Route
see [this issue](https://github.com/rectorphp/rector/issues/8384)
Closes https://github.com/rectorphp/rector/issues/8384
=> chore(symfony-routing): replace Symfony route annotation by attribute one

rules-tests/Symfony43/Rector/MethodCall/ConvertRenderTemplateShortNotationToBundleSyntaxRector/Fixture/skip_dynamic_variable.php.inc, rules/Symfony43/Rector/MethodCall/ConvertRenderTemplateShortNotationToBundleSyntaxRector.php
Fixes https://github.com/rectorphp/rector/issues/8449
=> [Symfony 4.3] Skip dynamic variable on ConvertRenderTemplateShortNotationToBundleSyntaxRector

rules/Symfony62/Rector/Class_/MessageHandlerInterfaceToAttributeRector.php
The `checkForServices()` function should return `null` if it has not actually changed the class
This is part of the SYMFONY_62 rule set
=> Fixes the MessageHandlerInterfaceToAttributeRector rule reported as always applied

config/sets/symfony/symfony62.php
That file does not exist :sweat_smile: 
https://github.com/symfony/symfony/tree/6.2/src/Symfony/Component/HttpFoundation/RequestMatcher
It was introduced in https://github.com/symfony/symfony/pull/47595
=> Fixes namespace of `ChainRequestMatcher`

config/sets/symfony/symfony52-validator-attributes.php
This  MR add a missing class to the list of configured "annotation to attributes" set list: the class `Symfony\Component\Serializer\Annotation\Context`, which was not yet configured.
=> Add missing 'Serializer/Context' class to the list of "annotation to attribute" rule

config/sets/symfony/symfony50-types.php, tests/Set/Symfony50/Fixture/skip_translator_that_already_uses_string_types.php.inc, tests/Set/Symfony50/Fixture/translator_not_using_params_types.php.inc
The 'trans' method in the Translator class has been updated to allow null values for 'domain' and 'locale' parameters.
Closes #592
=> Allow null values for domain and locale in Translator

rules-tests/CodeQuality/Rector/ClassMethod/TemplateAnnotationToThisRenderRector/Fixture/basic.php.inc, rules-tests/CodeQuality/Rector/ClassMethod/TemplateAnnotationToThisRenderRector/Fixture/empty_body.php.inc, rules-tests/CodeQuality/Rector/ClassMethod/TemplateAnnotationToThisRenderRector/Fixture/fixture3.php.inc, rules-tests/CodeQuality/Rector/ClassMethod/TemplateAnnotationToThisRenderRector/Fixture/fixture5.php.inc, rules-tests/CodeQuality/Rector/ClassMethod/TemplateAnnotationToThisRenderRector/Fixture/if_else_array_response.php.inc, rules-tests/CodeQuality/Rector/ClassMethod/TemplateAnnotationToThisRenderRector/Fixture/inner_return_with_only_vars.php.inc, rules-tests/CodeQuality/Rector/ClassMethod/TemplateAnnotationToThisRenderRector/Fixture/try_catch_array_response.php.inc, rules-tests/CodeQuality/Rector/ClassMethod/TemplateAnnotationToThisRenderRector/Fixture/with_only_vars.php.inc, src/Helper/TemplateGuesser.php
Currently, TemplateAnnotationToThisRenderRector is leaving the action method names camel cased. It was also leaving the controller capitalized with underscores. I believe this fix makes it work according to the docs at: https://symfony.com/bundles/SensioFrameworkExtraBundle/current/annotations/view.html
=> Fix TemplateGuesser to snake case controller classes and actions

rules-tests/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector/Fixture/skip_undefined_method.php.inc, rules/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector.php
Fixes https://github.com/rectorphp/rector/issues/8496
=> [CodeQuality] Skip complex structure cause undefined method on StringExtensionToConfigBuilderRector

docs/rector_rules_overview.md, rules-tests/Symfony44/Rector/MethodCall/AuthorizationCheckerIsGrantedExtractorRector/Fixture/controller_deny_array_value.php.inc, rules/Symfony44/Rector/MethodCall/AuthorizationCheckerIsGrantedExtractorRector.php, stubs/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php
Felt like this rule was missing the AbstractController implementation.
This PR will add `AbstractController::isGranted()` ~and `AbstractController::denyAccessUnlessGranted()`~ support
=> [Symfony 4.4] Updating AuthorizationCheckerIsGrantedExtractorRector

phpstan.neon, rules/SwiftMailer/Rector/ClassMethod/SwiftMessageToEmailRector.php
Ref https://github.com/rectorphp/rector-src/pull/5888
=> [PHPStan] Fix missingType.generics notice on phpstan.neon on PHPStan 1.11

config/sets/symfony/symfony64.php
Ref https://github.com/rectorphp/rector-symfony/issues/537
=> [Symfony 6.4] Add DataTransformerInterface return types

rules/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector.php
While converting my Symfony configs I ran into [this issue](https://github.com/rectorphp/rector/issues/8705).
=> feat: add web_profiler as config builder

rules-tests/Symfony61/Rector/Class_/CommandConfigureToAttributeRector/Fixture/hybrid.php.inc, rules/Symfony61/Rector/Class_/CommandConfigureToAttributeRector.php
When you already have a AsCommand attribute, but still have things that are done in `configure`, move them over.
=> Hybrid CommandConfigureToAttributeRector

composer.json, config/sets/symfony/symfony64.php, docs/rector_rules_overview.md, phpstan.neon, rules-tests/Configs/Rector/Class_/AutowireAttributeRector/AutowireAttributeRectorTest.php, rules-tests/Configs/Rector/Class_/AutowireAttributeRector/Fixture/another_configured_service.php.inc, rules-tests/Configs/Rector/Class_/AutowireAttributeRector/Fixture/fixture_duplicate.php.inc, rules-tests/Configs/Rector/Class_/AutowireAttributeRector/Fixture/positioned_arg.php.inc, rules-tests/Configs/Rector/Class_/AutowireAttributeRector/Fixture/skip_service_without_constructor.php.inc, rules-tests/Configs/Rector/Class_/AutowireAttributeRector/Source/configs/app_config.php, rules-tests/Configs/Rector/Class_/AutowireAttributeRector/Source/configs/position_arg.php, rules-tests/Configs/Rector/Class_/AutowireAttributeRector/config/configured_rule.php, rules/Configs/ConfigArrayHandler/SecurityAccessDecisionManagerConfigArrayHandler.php, rules/Configs/NodeAnalyser/ConfigServiceArgumentsResolver.php, rules/Configs/NodeAnalyser/SetServiceClassNameResolver.php, rules/Configs/NodeVisitor/CollectServiceArgumentsNodeVisitor.php, rules/Configs/Rector/Class_/AutowireAttributeRector.php, rules/Configs/ValueObject/ServiceArguments.php, rules/Symfony40/Rector/MethodCall/FormIsValidRector.php, rules/Symfony40/Rector/MethodCall/ProcessBuilderGetProcessRector.php, rules/Symfony61/Rector/Class_/CommandConfigureToAttributeRector.php, src/PhpParser/NamedSimplePhpParser.php, stubs/Symfony/Component/DependencyInjection/Loader/Configurator/ServiceConfigurator.php, stubs/Symfony/Component/DependencyInjection/Loader/Configurator/ServicesConfigurator.php
This is amazing feature from Symfony 6.1: https://symfony.com/blog/new-in-symfony-6-1-service-autowiring-attributes
All you need to do is provide path to your `/config` directory and rule is ready to go :+1: 
```php
// rector.php
use Rector\Config\RectorConfig;
use Rector\Symfony\Configs\Rector\Class_\AutowireAttributeRector;
return RectorConfig::configure()
->withConfiguredRule(AutowireAttributeRector::class, [
AutowireAttributeRector::CONFIGS_DIRECTORY => __DIR__ . '/configs',
]);
```
=> [Config] Add configurable AutowireAttributeRector to add #[Autowire(...)] to services

rules-tests/Symfony62/Rector/Class_/SecurityAttributeToIsGrantedAttributeRector/Fixture/single_is_granted.php.inc, rules-tests/Symfony62/Rector/Class_/SecurityAttributeToIsGrantedAttributeRector/Fixture/with_second_arg.php.inc, rules/Configs/NodeVisitor/CollectServiceArgumentsNodeVisitor.php, rules/Configs/Rector/Class_/AutowireAttributeRector.php, rules/Symfony62/Rector/Class_/SecurityAttributeToIsGrantedAttributeRector.php
Follow up to https://github.com/rectorphp/rector-symfony/pull/622
Covered cases:
```diff
-#[Security("is_granted('ROLE_ADMIN')")]
+#[\Symfony\Component\Security\Http\Attribute\IsGranted(attribute: 'ROLE_ADMIN')]
```
```diff
-#[Security("is_granted('ROLE_ADMIN', someArea)")]
+#[\Symfony\Component\Security\Http\Attribute\IsGranted(attribute: 'ROLE_ADMIN', subject: 'someArea')]
```
I've looked at the other cases, but due to it's stringy nature, we can't parse it and covert it into different structures.
This is the best we can automate, the rest would have to be dealt with manually.
<br>
Closes https://github.com/rectorphp/rector-symfony/issues/393
=> [Symfony 6.2] Improve SecurityAttributeToIsGrantedAttributeRector

config/sets/symfony/symfony64.php
Corrects the problem introduced #624 and fixes https://github.com/rectorphp/rector/issues/8730.
The correct return type is mixed (see https://github.com/symfony/symfony/blob/7.0/src/Symfony/Component/Form/DataTransformerInterface.php), the comment in https://github.com/rectorphp/rector-symfony/issues/537#issue-1957058803 where the change was based on was just an example for a particular scenario.
=> Correct return type definition for DataTransformerInterface

rules/CodeQuality/Rector/ClassMethod/ResponseReturnTypeControllerActionRector.php
Ref https://github.com/rectorphp/rector-symfony/pull/651#pullrequestreview-2207209590
the check already verified in above check:
```php
if (! $this->returnAnalyzer->hasOnlyReturnWithExpr($classMethod, $returns))
```
The fixture for it already exists at 
https://github.com/rectorphp/rector-symfony/blob/fcaedb34ce67a75db9ad18ed61c79de350837a58/rules-tests/CodeQuality/Rector/ClassMethod/ResponseReturnTypeControllerActionRector/Fixture/skip_no_return.php.inc#L10-L13
=> [CodeQuality] Remove no returns check on ResponseReturnTypeControllerActionRector

src/Set/SymfonySetList.php
Every other Symfony release has its set listed, so this looks like an oversight?
=> Add the Symfony 7.0 set to SymfonySetList.php

rules-tests/CodeQuality/Rector/ClassMethod/ResponseReturnTypeControllerActionRector/Fixture/skip_possible_return_array.php.inc, rules-tests/CodeQuality/Rector/ClassMethod/ResponseReturnTypeControllerActionRector/Fixture/skip_possible_return_array_or_response.php.inc, rules/CodeQuality/Rector/ClassMethod/ResponseReturnTypeControllerActionRector.php
ref https://github.com/rectorphp/rector-src/pull/6200#pullrequestreview-2207245293
it currently got incorrect return:
```diff
-    public function editAction(Request $request, $id = null)
+    public function editAction(Request $request, $id = null): ?array
Applied rules:
* ResponseReturnTypeControllerActionRector
```
This PR fix it.
=> [CodeQuality] Skip posible return array + response on ResponseReturnTypeControllerActionRector

rules-tests/Symfony42/Rector/New_/StringToArrayArgumentProcessRector/Fixture/do_not_convert_to_array_after_instantiation.php.inc, rules/Symfony42/Rector/New_/StringToArrayArgumentProcessRector.php
Corrects the problem introduced #646 
Closes https://github.com/rectorphp/rector-symfony/issues/646
=> Do not convert to array Process->setInput()

rules-tests/Symfony61/Rector/Class_/CommandConfigureToAttributeRector/Fixture/skip_abstract_class.php.inc, rules/Symfony61/Rector/Class_/CommandConfigureToAttributeRector.php
Fixes https://github.com/rectorphp/rector/issues/8799
=>  [Symfony 6.1] Skip abstract class on CommandConfigureToAttributeRector 

config/sets/symfony/symfony6/symfony-return-types.php
Return type declaration rules for `FormTypeInterface::buildForm` and `FormTypeInterface::configureOptions` were missing.
=> Added return type declaration rules for FormTypeInterface

config/sets/symfony/symfony72.php, src/Set/SetProvider/SymfonySetProvider.php, src/Set/SymfonySetList.php
Add `SYMFONY_72` Set list. It's not tagged yet but is `7.2.0-RC1`
=> [Symfony 7.2] Add SetList

rules-tests/DependencyInjection/Rector/Class_/GetBySymfonyStringToConstructorInjectionRector/Fixture/prefer_required_setter.php.inc
Fixture related to https://github.com/rectorphp/rector-src/pull/6652
=> Add fixture that prefers required if found

composer.json, rules-tests/DependencyInjection/Rector/Class_/GetBySymfonyStringToConstructorInjectionRector/Fixture/prefer_required_setter.php.inc
Ref https://github.com/rectorphp/rector-src/pull/6652
=> Update GetBySymfonyStringToConstructorInjectionRector fixture test to cover rector-srv:tv-readonly-add-ctor

rules/CodeQuality/Rector/ClassMethod/ActionSuffixRemoverRector.php
The `ActionSuffixRemoverRector` did not check if the new name was the same as the previous name and always tried to change it, resulting in the rule being reapplied with no need for it. This PR checks if the name needs to change and only updates the method if that is the case
=> Do not change method if name does not need to change

rules-tests/CodeQuality/Rector/Class_/InlineClassRoutePrefixRector/Fixture/attribute_routing_class_with_other_annotation.php.inc
@TomasVotruba this is failing fixture for `findManyByMany()` method at
https://github.com/rectorphp/rector-doctrine/commit/10aecf948db92008c29cefd4cbd1abc6fc777c55#commitcomment-152604254
=> [Symfony] Add attribute routing with mix other annotation

config/sets/symfony/symfony50.php, config/sets/symfony/symfony60.php
See: 
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Security/Core/User/UserProviderInterface.php vs https://github.com/symfony/symfony/blob/5.0/src/Symfony/Component/Security/Core/User/UserProviderInterface.php
and
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php vs https://github.com/symfony/symfony/blob/5.0/src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php
and
https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Config/Loader/LoaderInterface.php vs 
https://github.com/symfony/symfony/blob/6.0/src/Symfony/Component/Config/Loader/LoaderInterface.php
=> [SYMFONY 5 & 6] Security add missing param

composer.json, rules/DependencyInjection/Rector/Class_/CommandGetByTypeToConstructorInjectionRector.php, rules/DependencyInjection/Rector/Class_/ControllerGetByTypeToConstructorInjectionRector.php, rules/DependencyInjection/Rector/Class_/GetBySymfonyStringToConstructorInjectionRector.php, rules/DowngradeSymfony70/Rector/Class_/DowngradeSymfonyCommandAttributeRector.php, rules/Symfony43/Rector/ClassMethod/EventDispatcherParentConstructRector.php, rules/Symfony51/Rector/ClassMethod/CommandConstantReturnCodeRector.php, rules/Symfony61/Rector/StaticPropertyFetch/ErrorNamesPropertyToConstantRector.php, rules/Twig134/Rector/Return_/SimpleFunctionAndFilterRector.php, src/NodeAnalyzer/SymfonyTestCaseAnalyzer.php, src/TypeAnalyzer/ControllerAnalyzer.php
Ref 
- https://github.com/rectorphp/rector-src/pull/6775
=> Change deprecated ClassReflection::isSubClassOf() to ClassReflection::is() for PHPStan ^2.1.8

rules/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector.php
This PR adds the ability to auto convert the flysystem configuration
=> feat: add flysystem key

rules-tests/Configs/Rector/Closure/ServiceSetStringNameToClassNameRector/Fixture/skip_excluded_tag.php.inc, rules-tests/Configs/Rector/Closure/ServiceSetStringNameToClassNameRector/Source/ExcludedService.php, rules-tests/Configs/Rector/Closure/ServiceSetStringNameToClassNameRector/xml/services.xml, src/ValueObjectFactory/ServiceMapFactory.php
Since https://github.com/symfony/symfony/pull/46279, Symfony Dependency Injection add the "container.exclude" to auto-discovered classes that are excluded by manual config. I also have made a pull request https://github.com/symfony/symfony/pull/50452 which solved the problem with displaying services in the console. But Rector does not consider this in any way. This PR solves this problem and also closes the issue #709
=> Skip excluded tag in container

rules/CodeQuality/Rector/ClassMethod/TemplateAnnotationToThisRenderRector.php, rules/Symfony27/Rector/MethodCall/ChangeCollectionTypeOptionNameFromTypeToEntryTypeRector.php, rules/Symfony42/Rector/New_/StringToArrayArgumentProcessRector.php, rules/Symfony44/Rector/ClassMethod/ConsoleExecuteReturnIntRector.php
Fixes all cases found using the code in this PR https://github.com/rectorphp/rector-src/pull/6794
=> Fix cases where rule was applied even when no code changed

rules-tests/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector/Fixture/skip_no_extension.php.inc, src/NodeAnalyzer/SymfonyClosureExtensionMatcher.php
Fixes https://github.com/rectorphp/rector-symfony/issues/663
Ref https://getrector.com/demo/de776077-7f25-484f-bfea-1f5cf23a0443
instead of crash, this patch skip it.
=> [CodeQuality] Handle crash on no extensions on StringExtensionToConfigBuilderRector

composer.json, rules-tests/DependencyInjection/Rector/Class_/CommandGetByTypeToConstructorInjectionRector/CommandGetByTypeToConstructorInjectionRectorTest.php, rules-tests/DependencyInjection/Rector/Class_/GetBySymfonyStringToConstructorInjectionRector/Fixture/command_validator.php.inc, rules-tests/DependencyInjection/Rector/Class_/GetBySymfonyStringToConstructorInjectionRector/GetBySymfonyStringToConstructorInjectionRectorTest.php
Ref use of rector-src dev-follow-empty-param
- https://github.com/rectorphp/rector-src/pull/6855
use `#[RunClassInSeparateProcess]` as seems `ClassReflection` share cached across test parent.
=> Update fixture on parent construct empty usage

config/sets/symfony/symfony5/symfony52.php, config/sets/symfony/symfony5/symfony52/symfony52-dependency-injection.php, config/sets/symfony/symfony5/symfony52/symfony52-forms.php, config/sets/symfony/symfony5/symfony52/symfony52-http-foundation.php, config/sets/symfony/symfony5/symfony52/symfony52-mime.php, config/sets/symfony/symfony5/symfony52/symfony52-notifier.php, config/sets/symfony/symfony5/symfony52/symfony52-property-access.php, config/sets/symfony/symfony5/symfony52/symfony52-property-info.php, config/sets/symfony/symfony5/symfony52/symfony52-security-core.php, config/sets/symfony/symfony5/symfony52/symfony52-security-http.php, config/sets/symfony/symfony5/symfony52/symfony52-validator.php, rules/Symfony52/Rector/New_/PropertyAccessorCreationBooleanToFlagsRector.php, src/Set/SetProvider/Symfony5SetProvider.php
Ref https://github.com/rectorphp/rector/issues/9107
=> [symfony 5.2] split of configs per package

rules/CodeQuality/Rector/Class_/EventListenerToEventSubscriberRector.php, rules/Symfony30/Rector/ClassMethod/RemoveDefaultGetBlockPrefixRector.php
To clear use of protected property of NodeNameResolver on rector rules, use ClassNaming instead, Ref https://github.com/rectorphp/rector-symfony/pull/768#pullrequestreview-2834093699
=> Remove NodeNameResolver->getShortName() on Rector rules

rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/some_command.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/some_command_with_method_chaining.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/some_command_with_set_help.php.inc, src/Enum/SymfonyAttribute.php, tests/Set/Symfony73/Fixture/command_remove_config.php.inc
Ref https://github.com/symfony/symfony/blob/0b4d21c3f91dd2cd2cc49739ab31a1457cf001ea/src/Symfony/Component/Console/Attribute/Argument.php#L22
=> [Symfony 7.3] Fix typo Symfony Argument class attribute

rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/some_command.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/some_command_with_method_chaining.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/some_command_with_set_help.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/with_override.php.inc, rules/Symfony73/NodeAnalyzer/CommandArgumentsAndOptionsResolver.php, rules/Symfony73/NodeFactory/CommandInvokeParamsFactory.php, rules/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector.php, rules/Symfony73/ValueObject/CommandArgument.php, tests/Set/Symfony73/Fixture/command_remove_config.php.inc
=> [Symfony 7.3] Add Argument arguments: name, mode, description on InvokableCommandInputAttributeRector

rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/some_command.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/some_command_with_method_chaining.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/some_command_with_set_help.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/with_override.php.inc, rules/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector.php, tests/Set/Symfony73/Fixture/command_remove_config.php.inc
=> [Symfony 7.3] Keep $output param on InvokableCommandInputAttributeRector

rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/with_optional_argument.php.inc, rules/Symfony73/NodeFactory/CommandInvokeParamsFactory.php
=> [Symfony 7.3] Make nullable argument param type on Optional InputArgument::OPTIONAL on InvokableCommandInputAttributeRector

rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/some_command.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/some_command_with_method_chaining.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/some_command_with_set_help.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/with_optional_argument.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/with_override.php.inc, rules/Symfony73/NodeFactory/CommandInvokeParamsFactory.php, rules/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector.php, tests/Set/Symfony73/Fixture/command_remove_config.php.inc
=> [Symfony 7.3] Remove Argument argument: mode on InvokableCommandInputAttributeRector

rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/name_from_constant.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/some_command.php.inc, rules/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector.php
=> [Symfony 7.3] handle name from constant on InvokableCommandInputAttributeRector

rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/name_from_constant.php.inc, rules/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector.php
Ref https://github.com/rectorphp/rector-symfony/pull/777#pullrequestreview-2839570919
=> Fix ClassConstFetch use on InvokableCommandInputAttributeRector

rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/name_from_constant.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/some_command_with_set_help.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/with_optional_argument.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/with_override.php.inc, rules/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector.php
```
Warning: The magic method App\Command\HelloCommand::__invoke() must have public visibility
```
Ref #770
=> [Symfony 7.3] Make __invoke() public in InvokableCommandInputAttributeRector

rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/name_with_hyphen.php.inc, rules/Symfony73/NodeFactory/CommandInvokeParamsFactory.php, rules/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector.php
Normalize variable names by replacing hyphens with underscores in Symfony73 command argument and option processing
Fixes https://github.com/rectorphp/rector/issues/9205
=> fix: Normalize variable names by replacing hyphens with underscores in Symfony73 command argument and option processing

rules-tests/JMS/Rector/Class_/AccessTypeAnnotationToAttributeRector/Fixture/annotation_types.php.inc, rules/JMS/Rector/Class_/AccessTypeAnnotationToAttributeRector.php
Ref https://github.com/schmittjoh/serializer/issues/1531#issuecomment-1876719470
=> fix to type arg name

rules-tests/CodeQuality/Rector/MethodCall/StringCastDebugResponseRector/Fixture/skip_first_class_callable.php.inc, rules/CodeQuality/Rector/MethodCall/StringCastDebugResponseRector.php
Avoid error:
```
There was 1 failure:
1) Rector\Symfony\Tests\CodeQuality\Rector\MethodCall\StringCastDebugResponseRector\StringCastDebugResponseRectorTest::test with data set #0 ('/Users/samsonasik/www/rector-...hp.inc')
assert(!$this->isFirstClassCallable())
/Users/samsonasik/www/rector-symfony/vendor/nikic/php-parser/lib/PhpParser/Node/Expr/CallLike.php:32
/Users/samsonasik/www/rector-symfony/rules/CodeQuality/Rector/MethodCall/StringCastDebugResponseRector.php:86
```
=> [CodeQuality] Skip first class callable on StringCastDebugResponseRector

config/sets/symfony/symfony5/symfony51.php, config/sets/symfony/symfony5/symfony51/symfony51-http-foundation.php, tests/Set/Symfony51/Fixture/replace_cookie_with_same_site_parameter_value.php.inc, tests/Set/Symfony51/Symfony51Test.php, tests/Set/Symfony51/config/symfony51.php
See: https://github.com/rectorphp/rector/issues/9256
On hold see: https://github.com/rectorphp/rector-src/pull/7068
=> [SYMFONY 5.1] replace Cookie withSameSite argument values with constants

rules-tests/CodeQuality/Rector/MethodCall/ParameterBagTypedGetMethodCallRector/Fixture/skip_first_class_callable.php.inc, rules/CodeQuality/Rector/MethodCall/ParameterBagTypedGetMethodCallRector.php
Ref https://github.com/rectorphp/rector-symfony/pull/834#pullrequestreview-3173259447
=> [CodeQuality] Skip first class callable on ParameterBagTypedGetMethodCallRector

rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/name_with_hyphen.php.inc, rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/option_name_constant.php.inc, rules/Symfony73/NodeAnalyzer/CommandArgumentsResolver.php, rules/Symfony73/NodeAnalyzer/CommandOptionsResolver.php, rules/Symfony73/NodeFactory/CommandInvokeParamsFactory.php, rules/Symfony73/ValueObject/CommandArgument.php, rules/Symfony73/ValueObject/CommandOption.php
Fixes https://github.com/rectorphp/rector/issues/9345
=> [console] [7.3] Add const names in InvokableCommandInputAttributeRector + fix -_ naming to camel case
