config/sets/symfony/symfony32.php

Stripping quotation marks of argument default value

---

config/sets/jms/remove-jms-inject.php
phpstan.neon
src/Rector/Property/JMSInjectPropertyToConstructorInjectionRector.php
src/Set/JMSSetList.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Fixture/class_with_injects_35.php.inc
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Fixture/class_with_injects_7.php.inc
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Fixture/class_with_public_injects.php.inc
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Fixture/skip_parameter_inject.php.inc
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Fixture/some_controller.php.inc
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Fixture/some_controller_2.php.inc
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/JMSInjectPropertyToConstructorInjectionRectorTest.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Source/Bar.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Source/DifferntButFirstListed/Bar.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Source/DifferntButFirstListed/Foo.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Source/ExistingDependency.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Source/Foo.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Source/SomeEntityManager.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Source/SomeInterface.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Source/SomeParent.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Source/SomeProduct.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Source/SomeProductWithInterface.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Source/SomeProductWithParent.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Source/SomeProductWithTrait.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Source/SomeTrait.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Source/SomeTranslator.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/Source/SomeTranslatorInterface.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/config/configured_rule.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/xml/services.xml

Ref https://github.com/rectorphp/rector/issues/6246

[Property] Add JMSInjectPropertyToConstructorInjectionRector

---

config/config.php

[TASK] Add RenameClassNonPhpRector

---

config/sets/symfony/symfony52-validator-attributes.php
config/sets/symfony/symfony52.php
src/Set/SymfonySetList.php

cc @sabbelasichon Should be fine now :)

add Symfony Validator Attributes set

---

config/sets/twig/twig-underscore-to-namespace.php

https://github.com/rectorphp/rector/issues/6517

Twig_TemplateWrapper -> \Twig\TemplateWrapper

---

phpstan.neon
src/NodeFactory/BuilderFormNodeFactory.php
src/Rector/MethodCall/FormTypeInstanceToClassConstRector.php
tests/Rector/MethodCall/FormTypeInstanceToClassConstRector/Fixture/form_add_with_dependency.php.inc
tests/Rector/MethodCall/FormTypeInstanceToClassConstRector/Source/SomeTypeWithCtor.php

- bump to newer rector
- decopule FormTypeInstanceToClassConstRector external responbility

Symfony bump

---

config/sets/swiftmailer/swiftmailer-to-symfony-mailer.php
src/Rector/MethodCall/SwiftCreateMessageToNewEmailRector.php
src/Rector/MethodCall/SwiftSetBodyToHtmlPlainMethodCallRector.php
src/Set/SwiftmailerSetList.php
stubs/SwiftMailer/Swift_Mailer.php
stubs/SwiftMailer/Swift_Message.php
tests/Rector/MethodCall/SwiftSetBodyToHtmlPlainMethodCallRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/SwiftSetBodyToHtmlPlainMethodCallRector/SwiftSetBodyToHtmlPlainMethodCallRectorTest.php
tests/Rector/MethodCall/SwiftSetBodyToHtmlPlainMethodCallRector/config/configured_rule.php

Follow up to https://github.com/rectorphp/rector-symfony/pull/24
Ref https://github.com/rectorphp/rector/issues/6654

[SwiftMailer] Add SwiftSetBodyToHtmlPlainMethodCallRector

---

ecs.php
phpstan.neon
src/Rector/MethodCall/GetParameterToConstructorInjectionRector.php
src/Rector/MethodCall/MakeDispatchFirstArgumentEventRector.php
src/Rector/MethodCall/RedirectToRouteRector.php
src/Rector/MethodCall/ReflectionExtractorEnableMagicCallExtractorRector.php
src/Rector/MethodCall/SimplifyWebTestCaseAssertionsRector.php
src/Rector/MethodCall/StringFormTypeToClassRector.php
src/Rector/MethodCall/SwiftSetBodyToHtmlPlainMethodCallRector.php
src/Rector/MethodCall/ValidatorBuilderEnableAnnotationMappingRector.php
src/Rector/MethodCall/VarDumperTestTraitMethodArgsRector.php
src/Rector/New_/PropertyAccessorCreationBooleanToFlagsRector.php
src/Rector/New_/RootNodeTreeBuilderRector.php
src/Rector/New_/StringToArrayArgumentProcessRector.php
src/Rector/StaticCall/AddMessageToEqualsResponseCodeRector.php
src/Rector/StaticCall/ParseFileRector.php

Update to php-parser 4.13 - https://github.com/nikic/PHP-Parser/releases/tag/v4.13.0

[update] fix arg vs variadic php-parser 4.13 update

---

README.md
config/sets/symfony/symfony52-validator-attributes.php

https://github.com/rectorphp/rector/issues/6707

add groups annotation attribute

---

config/sets/symfony/symfony43.php
tests/Set/Symfony43/Fixture/event_fixture.php.inc
tests/Set/Symfony43/Symfony43Test.php
tests/Set/Symfony43/config/symfony43.php

Refs: https://github.com/rectorphp/rector-symfony/issues/29
Fixes: https://github.com/rectorphp/rector-symfony/issues/29

Get throwable instead of get exception

---

config/sets/symfony/level/up-to-symfony-54.php
config/sets/symfony/symfony54.php
src/Set/SymfonySetList.php

Closes https://github.com/rectorphp/rector/issues/6821

[Symfony 5.4] Add Validator nested attributes

---

src/Rector/New_/StringToArrayArgumentProcessRector.php
tests/Rector/New_/StringToArrayArgumentProcessRector/Fixture/do_not_convert_to_array_call_set_working_directory.php.inc
tests/Rector/New_/StringToArrayArgumentProcessRector/Fixture/skip_process_instance_methods.php.inc

[Symfony] Do not convert to array Process->setWorkingDirectory()

---

composer.json
src/NodeFactory/OnSuccessLogoutClassMethodFactory.php
src/Rector/New_/StringToArrayArgumentProcessRector.php
tests/Rector/Class_/LogoutSuccessHandlerToLogoutEventSubscriberRector/config/configured_rule.php
tests/Rector/New_/StringToArrayArgumentProcessRector/config/configured_rule.php

Discovered in https://github.com/rectorphp/rector-src/pull/1297

Fix param with method call override

---

config/sets/sensiolabs/framework-extra-61.php
rector.php
src/Set/SensiolabsSetList.php
src/TypeAnalyzer/JMSDITypeResolver.php

Covers https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/707
See https://github.com/rectorphp/rector/issues/6848

Add FrameworkExtraBundle with attributes set

---

config/sets/symfony/symfony60.php
docs/rector_rules_overview.md
rector.php
src/Rector/MethodCall/FormTypeInstanceToClassConstRector.php
src/Rector/MethodCall/GetDoctrineControllerToManagerRegistryRector.php
tests/Rector/MethodCall/GetDoctrineControllerToManagerRegistryRector/Fixture/some_class.php.inc
tests/Rector/MethodCall/GetDoctrineControllerToManagerRegistryRector/GetDoctrineControllerToManagerRegistryRectorTest.php
tests/Rector/MethodCall/GetDoctrineControllerToManagerRegistryRector/config/configured_rule.php

Ref https://github.com/rectorphp/rector-symfony/issues/94

[Symfony 6.0] Add GetDoctrineControllerToManagerRegistryRector

---

config/sets/symfony/symfony60.php
docs/rector_rules_overview.md
src/Rector/MethodCall/GetDoctrineControllerToManagerRegistryRector.php
src/Rector/MethodCall/GetHelperControllerToServiceRector.php
src/TypeAnalyzer/ControllerAnalyzer.php
tests/Rector/MethodCall/GetHelperControllerToServiceRector/Fixture/dispatch_message.php.inc
tests/Rector/MethodCall/GetHelperControllerToServiceRector/Fixture/some_class.php.inc
tests/Rector/MethodCall/GetHelperControllerToServiceRector/GetHelperControllerToServiceRectorTest.php
tests/Rector/MethodCall/GetHelperControllerToServiceRector/config/configured_rule.php

Closes https://github.com/rectorphp/rector-symfony/issues/94

[Symfony 6.0] Add dispatchMessage() to service in controller

---

composer.json
stubs/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php

ref https://github.com/rectorphp/rector-src/pull/1812#issuecomment-1038330946 on using latest symfony 6

[Stub][Test] Fix Tests error for AbstractController stub usage on using latest symfony 6

---

composer.json

per https://github.com/rectorphp/rector-src/pull/1812 merged after change ConfigurableCallValuesCollectingPhpFileLoader return type after update latest symfony 6

Back to rector-src dev-main without commit hash

---

src/NodeAnalyzer/DependencyInjectionMethodCallAnalyzer.php
tests/Rector/MethodCall/ContainerGetToConstructorInjectionRector/Fixture/some_translator_exists.php.inc
tests/Rector/MethodCall/ContainerGetToConstructorInjectionRector/Fixture/some_translator_exists2.php.inc

Fixes https://github.com/rectorphp/rector-symfony/issues/111

[Symfony] Handle property exists on ContainerGetToConstructorInjectionRector

---

src/Bridge/NodeAnalyzer/ControllerMethodAnalyzer.php
tests/Rector/ClassMethod/ActionSuffixRemoverRector/Fixture/fixture_no_controller.php.inc
tests/Rector/ClassMethod/ActionSuffixRemoverRector/Fixture/fixture_private.php.inc
tests/Rector/ClassMethod/ActionSuffixRemoverRector/Fixture/fixture_static.php.inc

Controller-Actions can only be public, non static functions

---

docs/rector_rules_overview.md
src/Rector/BinaryOp/ResponseStatusCodeRector.php
stubs/Symfony/Bundle/FrameworkBundle/Client.php
stubs/Symfony/Component/HttpKernel/Client.php
tests/Rector/BinaryOp/ResponseStatusCodeRector/Fixture/test_assert_equals.php.inc

Based on https://twitter.com/VotrubaT/status/1503315554127466498

Add test assert support to ResponseStatusCodeRector

---

src/Rector/BinaryOp/ResponseStatusCodeRector.php
src/ValueObject/ConstantMap/SymfonyResponseConstantMap.php
stubs/Symfony/Bundle/FrameworkBundle/Controller/Controller.php
tests/Rector/BinaryOp/ResponseStatusCodeRector/Fixture/fixture.php.inc
tests/Rector/BinaryOp/ResponseStatusCodeRector/Fixture/new_response.php.inc
tests/Rector/BinaryOp/ResponseStatusCodeRector/Fixture/redirect_in_controller.php.inc
tests/Rector/BinaryOp/ResponseStatusCodeRector/Fixture/skip_no_arg_new_response.php.inc

- add test case to redirect() to code
- add redirect() method
- add new response

Add new response 2nd arg 

---

src/Rector/MethodCall/LiteralGetToRequestClassConstantRector.php
tests/Rector/MethodCall/LiteralGetToRequestClassConstantRector/Fixture/send_client_request.php.inc
tests/Rector/MethodCall/LiteralGetToRequestClassConstantRector/Fixture/skip_already.php.inc

- add client->request() support
- add skipped case

Add client->request() for METHOD_GET

---

ecs.php
phpstan.neon
rector.php
src/NodeAnalyzer/SymfonyControllerFilter.php
src/NodeFactory/InvokableControllerClassFactory.php
src/Rector/Class_/InvokableControllerRector.php
stubs/Symfony/Bundle/FrameworkBundle/Controller/Controller.php
tests/Rector/Class_/InvokableControllerRector/DependencyInvokableControllerRectorTest.php
tests/Rector/Class_/InvokableControllerRector/FixtureDependency/Expected/DependencyDetailController.php
tests/Rector/Class_/InvokableControllerRector/FixtureDependency/Expected/DependencyListController.php
tests/Rector/Class_/InvokableControllerRector/FixtureDependency/dependency_controller.php.inc
tests/Rector/Class_/InvokableControllerRector/Source/NormalRepository.php

Follow up to https://github.com/rectorphp/rector-symfony/pull/135

Add constructor support to InvokableControllerRector

---

src/NodeAnalyzer/InvokableAnalyzer/ActiveClassElementsClassMethodResolver.php
src/NodeFactory/InvokableControllerClassFactory.php
src/ValueObject/InvokableController/ActiveClassElements.php
tests/Rector/Class_/InvokableControllerRector/FixtureDependency/Expected/DependencyDetailController.php
tests/Rector/Class_/InvokableControllerRector/FixtureDependency/Expected/DependencyListController.php
tests/Rector/Class_/InvokableControllerRector/FixtureDependency/dependency_controller.php.inc
tests/Rector/Class_/InvokableControllerRector/Source/LeftRepository.php
tests/Rector/Class_/InvokableControllerRector/Source/RightRepository.php

- add separated test dependencies test fixture
- 2nd fixture
- add used property names
- add stmt removal

Improve InvokableControllerRector

---

composer.json
src/Rector/Class_/InvokableControllerRector.php

Ref https://github.com/rectorphp/rector-src/pull/2038

Use RemovedAndAddedFilesCollector directly

---

config/config.php
rector.php
src/DataProvider/ServiceMapProvider.php
src/Rector/MethodCall/StringFormTypeToClassRector.php
tests/Rector/Class_/EventListenerToEventSubscriberRector/config/config_with_parameter.php
tests/Rector/MethodCall/ContainerGetToConstructorInjectionRector/config/configured_rule.php
tests/Rector/MethodCall/GetToConstructorInjectionRector/config/configured_rule.php
tests/Rector/MethodCall/StringFormTypeToClassRector/config/xml_path_config.php
tests/Rector/Property/JMSInjectPropertyToConstructorInjectionRector/config/configured_rule.php

- fix cs
- use xml path parameter

Deprecate XML path option

---

config/sets/symfony/annotations-to-attributes.php
config/sets/symfony/symfony52.php
config/sets/symfony/symfony53.php
config/sets/symfony/symfony54.php
config/sets/symfony/symfony60.php

Revert https://github.com/rectorphp/rector-symfony/commit/7dd7cdf3850ff4b0a7839fcf24bb4c26138044de#diff-14ee97bddeec815fe39cfb505622628326446e808d65b8b4fd95163cb4018079 that generated by `UpgradeRectorConfigRector`
Possibly part of https://github.com/rectorphp/rector-src/pull/2111 issue.

Revert ruleWithConfig after sets

---

composer.json
src/DataProvider/ServiceMapProvider.php
src/Printer/NeighbourClassLikePrinter.php
src/Rector/Class_/InvokableControllerRector.php

Related to https://github.com/rectorphp/rector-src/pull/2136

Improve BetterNodeFinder

---

src/Rector/MethodCall/LiteralGetToRequestClassConstantRector.php
stubs/Symfony/Component/BrowserKit/AbstractBrowser.php

Closes https://github.com/rectorphp/rector/issues/7135

Skip Symfony\Component\HttpKernel\Client object check if Symfony\Component\BrowserKit\AbstractBrowser is missing

---

src/NodeFinder/EmptyReturnNodeFinder.php
tests/Rector/ClassMethod/TemplateAnnotationToThisRenderRector/Fixture/inner_return_with_only_vars.php.inc

ref https://github.com/rectorphp/rector-symfony/pull/165#discussion_r867564523

[Symfony] Add inner function support on TemplateAnnotationToThisRenderRector

---

src/Rector/Class_/CommandPropertyToAttributeRector.php
tests/Rector/Class_/CommandPropertyToAttributeRector/CommandPropertyToAttributeRectorTest.php
tests/Rector/Class_/CommandPropertyToAttributeRector/Fixture/command.php.inc
tests/Rector/Class_/CommandPropertyToAttributeRector/Fixture/commandWithDescription.php.inc
tests/Rector/Class_/CommandPropertyToAttributeRector/config/configured_rule.php

My first PR that adds a Rector, so happy to get some feedback.
Fixes #159

Add CommandPropertyToAttributeRector

---

rector.php
src/Bridge/Symfony/Routing/SymfonyRoutesProvider.php
src/Contract/Bridge/Symfony/Routing/SymfonyRoutesProviderInterface.php
src/Rector/ClassMethod/AddRouteAnnotationRector.php
src/ValueObject/SymfonyRouteMetadata.php

Follow up to https://github.com/rectorphp/rector-symfony/pull/173
Ref https://github.com/rectorphp/rector-symfony/issues/168

Tiny improvements of AddRouteAnnotationRector

---

src/NodeFactory/Annotations/DoctrineAnnotationKeyToValuesResolver.php
tests/Rector/Class_/LoadValidatorMetadataToAnnotationRector/Fixture/class_validation_with_array.php.inc

- single item
- fix implicit key in array

[Validator] Fix quoting of implicit key in array of assert annotation

---

src/Helper/TemplateGuesser.php
src/NodeAnalyzer/Annotations/MethodCallAnnotationAssertResolver.php
src/Rector/Class_/LoadValidatorMetadataToAnnotationRector.php
src/ValueObject/ValidatorAssert/ClassMethodAndAnnotation.php
tests/Rector/Class_/LoadValidatorMetadataToAnnotationRector/Fixture/method_is_bool.php.inc

- [Validator] Add is/has method supoprt
- refactor nullsafe to explicit types, cleaner to read

[Validator] Add is/has method support

---

config/sets/symfony/symfony30.php
tests/Rector/Class_/FormTypeWithDependencyToOptionsRector/Fixture/fail_with_missing_build_form.php.inc

As asked in #180, but I have no clue on how to make a correct failing test fixture for this :(

Fix FormTypeWithDependencyToOptionsRector configuration

---

docs/rector_rules_overview.md
easy-ci.php
phpstan.neon
rector.php
src/Rector/Class_/MagicClosureTwigExtensionToNativeMethodsRector.php
stubs/Twig/Extension/AbstractExtension.php
stubs/Twig/Extension/ExtensionInterface.php
tests/Rector/Class_/MagicClosureTwigExtensionToNativeMethodsRector/Fixture/inlined_short_closure.php.inc
tests/Rector/Class_/MagicClosureTwigExtensionToNativeMethodsRector/Fixture/some_class.php.inc
tests/Rector/Class_/MagicClosureTwigExtensionToNativeMethodsRector/MagicClosureTwigExtensionToNativeMethodsRectorTest.php
tests/Rector/Class_/MagicClosureTwigExtensionToNativeMethodsRector/config/configured_rule.php

- misc
- Add MagicClosureTwigExtensionToNativeMethodsRector

Add MagicClosureTwigExtensionToNativeMethodsRector

---

src/Rector/ClassMethod/MergeMethodAnnotationToRouteAnnotationRector.php

@TomasVotruba continue https://github.com/rectorphp/rector-src/pull/2558#issuecomment-1164838756

Fix @return on MergeMethodAnnotationToRouteAnnotationRector::resolveMethods()

---

docs/rector_rules_overview.md
src/Rector/MethodCall/AuthorizationCheckerIsGrantedExtractorRector.php

Improve doc formatting and fix duplicated ROLE_USER instead of ROLE_ADMIN

Fix documentation on AuthorizationCheckerIsGrantedExtractorRector

---

config/sets/symfony/symfony52.php

continue of https://github.com/rectorphp/rector-symfony/pull/204. `AddParamTypeDeclarationRector` need to be merged as well.

Another fix merge config on symfony 5.2 config set

---

config/sets/symfony/symfony6/symfony-return-types.php
tests/Set/Symfony60/Fixture/router_get_route_collection.php.inc
tests/Set/Symfony60/Fixture/router_interface_get_route_collection.php.inc
tests/Set/Symfony60/Symfony60Test.php
tests/Set/Symfony60/config/symfony60.php

[Symfony60] Fix added return type for Router::getRouteCollection

---

config/sets/symfony/symfony30.php

Fixes https://github.com/rectorphp/rector/issues/7313

Fix order of arguments

---

src/Bridge/Symfony/ContainerServiceProvider.php

fixes $serviceName

---

rector.php
tests/Rector/Class_/InvokableControllerRector/DependencyInvokableControllerRectorTest.php
tests/Rector/Class_/InvokableControllerRector/SplitInvokableControllerRectorTest.php
tests/Rector/Class_/MakeCommandLazyRector/Php80Test.php

ref https://github.com/rectorphp/rector-src/pull/2889

[Dep] Update tests to use string path instead of SmartFileInfo

---

config/sets/symfony/symfony53.php
src/Rector/Class_/CommandDescriptionToPropertyRector.php
src/Rector/Class_/MakeCommandLazyRector.php
tests/Rector/Class_/CommandDescriptionToPropertyRector/CommandDescriptionToPropertyRectorTest.php
tests/Rector/Class_/CommandDescriptionToPropertyRector/Fixture/set_description_fluent.php.inc
tests/Rector/Class_/CommandDescriptionToPropertyRector/Fixture/set_description_fluent_chain.php.inc
tests/Rector/Class_/CommandDescriptionToPropertyRector/Fixture/skip_description_already_property.php.inc
tests/Rector/Class_/CommandDescriptionToPropertyRector/Fixture/skip_non_description_setter.php.inc
tests/Rector/Class_/CommandDescriptionToPropertyRector/config/configured_rule.php

See https://github.com/rectorphp/rector-symfony/issues/229

[Symfony53] Add CommandDescriptionToPropertyRector

---

config/sets/symfony/symfony43.php
src/NodeAnalyzer/SymfonyTestCaseAnalyzer.php
src/Rector/ClassMethod/ConsoleExecuteReturnIntRector.php
src/Rector/Class_/CommandDescriptionToPropertyRector.php
src/Rector/Return_/SimpleFunctionAndFilterRector.php
src/TypeAnalyzer/ControllerAnalyzer.php

[Symfony43] Add missing rule WebTestCaseAssertIsSuccessfulRector #249

---

src/Rector/Class_/CommandDescriptionToPropertyRector.php
tests/Rector/Class_/CommandDescriptionToPropertyRector/Fixture/set_description_at_top.php.inc
tests/Rector/Class_/CommandDescriptionToPropertyRector/Fixture/set_description_fluent.php.inc
tests/Rector/Class_/CommandDescriptionToPropertyRector/Fixture/set_description_fluent_chain.php.inc
tests/Rector/Class_/CommandDescriptionToPropertyRector/Fixture/skip_description_already_property.php.inc

Set description property in the correct location.

[CommandDescriptionToPropertyRector] Correct location for description

---

config/sets/twig/level/up-to-twig-112.php
config/sets/twig/level/up-to-twig-127.php
config/sets/twig/level/up-to-twig-134.php
config/sets/twig/level/up-to-twig-140.php
config/sets/twig/level/up-to-twig-20.php
config/sets/twig/level/up-to-twig-240.php
src/Set/TwigLevelSetList.php

Seeing Symfony have a LevelSetList, I thought it might be useful for Twig as well

Adding TwigLevelSetList

---

config/sets/symfony/level/up-to-symfony-62.php
config/sets/symfony/symfony43.php
config/sets/symfony/symfony60.php
config/sets/symfony/symfony62.php
src/Set/SymfonyLevelSetList.php
src/Set/SymfonySetList.php
tests/Set/Symfony62/Fixture/replace_sensio_cache.php.inc
tests/Set/Symfony62/Fixture/replace_sensio_is_granted.php.inc
tests/Set/Symfony62/Fixture/replace_sensio_template.php.inc
tests/Set/Symfony62/Symfony62Test.php
tests/Set/Symfony62/config/symfony62.php

Replace `IsGranted`, `Cache` and `Template`

[Symfony62] Replace attributes #264

---

src/Rector/New_/StringToArrayArgumentProcessRector.php

Fixes https://github.com/rectorphp/rector/issues/7613

Fix bug with privatesCaller not found

---

src/Rector/ClassMethod/CommandConstantReturnCodeRector.php
tests/Rector/ClassMethod/CommandConstantReturnCodeRector/Fixture/replace_fail.php.inc
tests/Rector/ClassMethod/CommandConstantReturnCodeRector/Fixture/replace_invalid.php.inc
tests/Rector/ClassMethod/CommandConstantReturnCodeRector/Fixture/replace_with_constant.php.inc

Ref https://github.com/rectorphp/rector-symfony/pull/296/files#r1032545979

Fix FQCN constant on CommandConstantReturnCodeRector

---

src/Rector/MethodCall/WebTestCaseAssertIsSuccessfulRector.php
src/Rector/MethodCall/WebTestCaseAssertResponseCodeRector.php
src/Rector/MethodCall/WebTestCaseAssertSelectorTextContainsRector.php
tests/Rector/MethodCall/VarDumperTestTraitMethodArgsRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/WebTestCaseAssertIsSuccessfulRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/WebTestCaseAssertResponseCodeRector/Fixture/http_code.php.inc
tests/Rector/MethodCall/WebTestCaseAssertResponseCodeRector/Fixture/skip_200_response.php.inc
tests/Rector/MethodCall/WebTestCaseAssertSelectorTextContainsRector/Fixture/handle_static_calls.php.inc
tests/Rector/StaticCall/AddMessageToEqualsResponseCodeRector/Fixture/skip_already_has_message_param.php.inc

Refactor param message and also refector static asserts

Correctly refector argument `message` and support static func

---

src/Rector/ClassMethod/ResponseReturnTypeControllerActionRector.php
tests/Rector/ClassMethod/ResponseReturnTypeControllerActionRector/Fixture/skip_no_return.php.inc

- add failing fixture
- skip no return class methods

Skip ClassMethod with no return

---

src/Rector/MethodCall/WebTestCaseAssertResponseCodeRector.php
tests/Rector/MethodCall/WebTestCaseAssertResponseCodeRector/Fixture/http_code.php.inc

[WebTestCaseAssertResponseCodeRector] Correctly handle setting null

---

config/sets/symfony/symfony62.php

See https://github.com/symfony/symfony/pull/48554

Symfony 6.2: Fix Security constants rector

---

src/Rector/MethodCall/WebTestCaseAssertIsSuccessfulRector.php
src/Rector/MethodCall/WebTestCaseAssertResponseCodeRector.php
src/Rector/MethodCall/WebTestCaseAssertSelectorTextContainsRector.php
tests/Rector/MethodCall/WebTestCaseAssertIsSuccessfulRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/WebTestCaseAssertResponseCodeRector/Fixture/http_code.php.inc
tests/Rector/MethodCall/WebTestCaseAssertSelectorTextContainsRector/Fixture/contains_crawler.php.inc

Todo handle all phpunit asserts that can have 'sprintf' function

Handle sprintf custom messages for asserts

---

config/sets/symfony/symfony62.php
src/Rector/Class_/MakeCommandLazyRector.php

This class has been moved in https://github.com/symfony/symfony/pull/47760

Fix class name for Symfony 6.2

---

config/sets/symfony/symfony33.php
tests/Set/Symfony33/Fixture/add_compile_resolve_env_placeholders_argument.php.inc
tests/Set/Symfony33/Symfony33Test.php
tests/Set/Symfony33/config/symfony33.php

* Corrected the position of the argument that should be added
* Corrected the default value of the argument
* Set the name of the argument that is added
* Added unit test

[SYMFONY33] Fix configuration for the ArgumentAdderRector of the compile method of the ContainerBuilder (#327)

---

src/Rector/Closure/ServicesSetNameToSetTypeRector.php
tests/Rector/Closure/ServicesSetNameToSetTypeRector/Fixture/skip_same_type_twice.php.inc

- add fixture
- skip duplicated type usage

Skip same type twice on ServicesSetNameToSetTypeRector

---

composer.json
docs/rector_rules_overview.md

Per discussion on https://github.com/rectorphp/rector/issues/7752#issuecomment-1413397028

Remove check-markdown command from composer fix-cs and composer docs

---

composer.json
tests/Rector/Class_/InvokableControllerRector/DependencyInvokableControllerRectorTest.php
tests/Rector/Class_/InvokableControllerRector/SplitInvokableControllerRectorTest.php

Mirror to https://github.com/rectorphp/rector-src/pull/3338

Make test paths explicit

---

config/sets/symfony/symfony43.php
config/sets/symfony/symfony44.php
tests/Set/Symfony43/Fixture/event_fixture.php.inc
tests/Set/Symfony44/Fixture/event_fixture.php.inc
tests/Set/Symfony44/Symfony44Test.php
tests/Set/Symfony44/config/symfony44.php

Closes https://github.com/rectorphp/rector-symfony/issues/346

[SYMFONY43] Move to 4.4 changes in GetResponseForExceptionEvent

---

config/sets/sensiolabs/framework-extra-61.php

Came across some duplicate rules, made more sense to use the other set

[FRAMEWORK_EXTRA_61] Replacing rules with existing set

---

src/Rector/ClassMethod/ParamConverterAttributeToMapEntityAttributeRector.php
tests/Rector/ClassMethod/ParamConverterAttributeToMapEntityAttributeRector/Fixture/replace_paramconverter_named_arguments.php.inc

In addition to PR #291 
ping @stephanvierkant

Maintain named arguments for ParamConverter

---

config/sets/symfony/symfony53.php

See https://github.com/rectorphp/rector-symfony/issues/352

Change param in Datamapper to Traversable

---

src/Rector/ClassMethod/AddRouteAnnotationRector.php
tests/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/invokable_controller.php.inc
tests/Rector/ClassMethod/AddRouteAnnotationRector/config/routes.json

Fixes #301 
Should also make #338 pass

Adding check for invokable controller

---

tests/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/double_route.php.inc
tests/Rector/ClassMethod/AddRouteAnnotationRector/config/routes.json

Adding fixtures for routes to same controller method

---

src/Rector/Closure/ServiceArgsToServiceNamedArgRector.php
tests/Rector/Closure/ServiceArgsToServiceNamedArgRector/Fixture/handle_ctor_of_parent_parent.php.inc
tests/Rector/Closure/ServiceArgsToServiceNamedArgRector/Fixture/handle_service_too.php.inc
tests/Rector/Closure/ServiceArgsToServiceNamedArgRector/Source/GrandChildClassWithConstructor.php

- add fixture with grandchild
- handle service ref too

Handle service too in ServiceArgsToServiceNamedArgRector

---

config/sets/symfony/symfony53.php

Do not include invalid file in symfony53 set

---

config/sets/symfony/symfony62.php
src/Helper/MessengerHelper.php
src/Rector/Class_/MessageHandlerInterfaceToAttributeRector.php
tests/Rector/Class_/MessageHandlerInterfaceToAttributeRector/Fixture/extra-attribute.php.inc
tests/Rector/Class_/MessageHandlerInterfaceToAttributeRector/Fixture/manual-service_messagehandler.php.inc
tests/Rector/Class_/MessageHandlerInterfaceToAttributeRector/Fixture/messagehandler.php.inc
tests/Rector/Class_/MessageHandlerInterfaceToAttributeRector/Fixture/skip-attribute.php.inc
tests/Rector/Class_/MessageHandlerInterfaceToAttributeRector/MessageHandlerToAttributeRectorTest.php
tests/Rector/Class_/MessageHandlerInterfaceToAttributeRector/config/configured_rule.php
tests/Rector/Class_/MessageHandlerInterfaceToAttributeRector/xml/services.xml

[SYMFONY62] Replace MessageHandlerInterface with asMessageHandler

---

composer.json

Since PR:
- https://github.com/rectorphp/rector-src/pull/3460
has merged.

Back to use rector-src dev-main

---

docs/rector_rules_overview.md
src/Rector/Class_/MessageHandlerInterfaceToAttributeRector.php
tests/Rector/Class_/MessageHandlerInterfaceToAttributeRector/Fixture/skip-method-attribute.php.inc
tests/Rector/Class_/MessageHandlerInterfaceToAttributeRector/xml/services.xml

[MessageHandlerInterfaceToAttributeRector] Adding check for method

---

tests/Rector/Closure/ServiceSettersToSettersAutodiscoveryRector/MinimalSharedStringSolverTest.php

as requested in https://github.com/rectorphp/rector-symfony/pull/379/files#r1135336606

Added MinimalSharedStringSolver tests

---

src/Helper/CommandHelper.php
src/NodeAnalyzer/FormAddMethodCallAnalyzer.php
src/Rector/BinaryOp/ResponseStatusCodeRector.php
src/Rector/ClassMethod/FormTypeGetParentRector.php
src/Rector/Class_/ChangeFileLoaderInExtensionAndKernelRector.php
src/Rector/Class_/CommandDescriptionToPropertyRector.php
src/Rector/Class_/FormTypeWithDependencyToOptionsRector.php
src/Rector/Class_/MakeCommandLazyRector.php
src/Rector/Closure/ContainerGetNameToTypeInTestsRector.php
src/Rector/Closure/ServiceArgsToServiceNamedArgRector.php
src/Rector/Closure/ServiceSettersToSettersAutodiscoveryRector.php
src/Rector/MethodCall/ContainerBuilderCompileEnvArgumentRector.php
src/Rector/MethodCall/ContainerGetToConstructorInjectionRector.php
src/Rector/MethodCall/DefinitionAliasSetPrivateToSetPublicRector.php
src/Rector/MethodCall/FormBuilderSetDataMapperRector.php
src/Rector/MethodCall/FormIsValidRector.php
src/Rector/MethodCall/GetToConstructorInjectionRector.php
src/Rector/MethodCall/LiteralGetToRequestClassConstantRector.php
src/Rector/MethodCall/MakeDispatchFirstArgumentEventRector.php
src/Rector/MethodCall/MaxLengthSymfonyFormOptionToAttrRector.php
src/Rector/MethodCall/ProcessBuilderGetProcessRector.php
src/Rector/MethodCall/ReflectionExtractorEnableMagicCallExtractorRector.php
src/Rector/MethodCall/SwiftSetBodyToHtmlPlainMethodCallRector.php
src/Rector/MethodCall/ValidatorBuilderEnableAnnotationMappingRector.php
src/Rector/MethodCall/VarDumperTestTraitMethodArgsRector.php
src/Rector/MethodCall/WebTestCaseAssertResponseCodeRector.php
src/Rector/New_/RootNodeTreeBuilderRector.php

Apply changes from https://github.com/rectorphp/rector-src/pull/3502 here as well

Performance: Reduce isObjectType calls

---

src/FormHelper/FormTypeStringToTypeProvider.php
src/Rector/MethodCall/VarDumperTestTraitMethodArgsRector.php

Reverts rectorphp/rector-symfony#391
/cc @staabm

Revert VarDumperTestTraitMethodArgsRector: Autoload the test-trait

---

src/Rector/Class_/MagicClosureTwigExtensionToNativeMethodsRector.php

counterpart of https://github.com/rectorphp/rector-src/pull/3835

ArrayCallableMethodMatcher type fixes

---

tests/Rector/Class_/InvokableControllerRector/FixtureSplit/Expected/SomeClassNoNamespaceDetailController.php
tests/Rector/Class_/InvokableControllerRector/FixtureSplit/Expected/SomeClassNoNamespaceListController.php
tests/Rector/Class_/InvokableControllerRector/FixtureSplit/some_class_no_namespace.php.inc
tests/Rector/Class_/InvokableControllerRector/SplitInvokableControllerNoNamespaceRectorTest.php

@TomasVotruba this is test fixture for PR on rector-src on negative key on apply declare(strict_types=1) on FileWithoutNamespace_:
- https://github.com/rectorphp/rector-src/pull/3899

[Test] Add test for no namespace with declare(strict_types=1) on InvokableControllerRector

---

phpunit.xml
src/Enum/SensioAttribute.php
src/Enum/SymfonyAnnotation.php
src/Rector/ClassMethod/MergeMethodAnnotationToRouteAnnotationRector.php
src/Rector/ClassMethod/ParamConverterAttributeToMapEntityAttributeRector.php
src/Rector/ClassMethod/ResponseReturnTypeControllerActionRector.php

Ref https://github.com/rectorphp/rector/issues/7947

Remove PARENT_NODE from ParamConverterAttributeToMapEntityAttributeRector

---

phpunit.xml
src/Rector/ClassMethod/ConsoleExecuteReturnIntRector.php
src/Rector/ClassMethod/ParamConverterAttributeToMapEntityAttributeRector.php
src/Rector/Class_/CommandPropertyToAttributeRector.php

Ref https://github.com/rectorphp/rector/issues/7947

Remove PARENT_NODE from ConsoleExecuteReturnIntRector

---

src/Rector/New_/StringToArrayArgumentProcessRector.php

PHPStan 1.10.16 just released https://github.com/phpstan/phpstan/releases/tag/1.10.16
This PR fix PHPStan notice.
https://github.com/rectorphp/rector-src/actions/runs/5175202928/jobs/9322494541?pr=4074#step:7:18

Fix PHPStan notice on PHPStan 1.10.16

---

composer.json
src/NodeFactory/GetSubscribedEventsClassMethodFactory.php

Ref https://github.com/rectorphp/rector-src/pull/4215

Update PhpDocTypeChanger call arguments usage per use of DocblockUpdater

---

.gitattributes

Avoid rules-tests committed on build https://github.com/rectorphp/rector/commit/9ce469b35cdca60c6b5b471075bf14b9d62d0099#diff-274bfc5e848613fb676bae91dfd3915d34498ad33402c2743d209e332ee61c31

Add rules-tests to .gitattributes

---

docs/rector_rules_overview.md
phpstan.neon
rules-tests/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector/Fixture/some_class.php.inc
rules-tests/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector/Source/SomeUserProvider.php
rules-tests/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector/StringExtensionToConfigBuilderRectorTest.php
rules-tests/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector/config/configured_rule.php
rules/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector.php

Ref https://symfony.com/blog/new-in-symfony-5-3-config-builder-classes

[CodeQuality] Add StringExtensionToConfigBuilderRector

---

docs/rector_rules_overview.md
rules-tests/Symfony62/Rector/Class_/MessageSubscriberInterfaceToAttributeRector/Fixture/messagesubscriber-yield.php.inc
rules-tests/Symfony62/Rector/Class_/MessageSubscriberInterfaceToAttributeRector/MessageSubscriberInterfaceToAttributeRectorTest.php
rules-tests/Symfony62/Rector/Class_/MessageSubscriberInterfaceToAttributeRector/config/configured_rule.php
rules/Symfony62/Rector/Class_/MessageSubscriberInterfaceToAttributeRector.php
src/Helper/MessengerHelper.php

[SYMFONY62] Replace MessageSubscriberInterface with AsMessageHandler attributes

---

tests/Set/Symfony32/Fixture/skip_default_values_compiler_pass.php.inc
tests/Set/Symfony32/Symfony32Test.php
tests/Set/Symfony32/config/symfony32.php

Failing test for #397
I'll see if I can figure this out 🙂

Unnecessarily default values for addCompilerPass (#397)

---

config/sets/symfony/symfony62.php
docs/rector_rules_overview.md
rules-tests/Symfony62/Rector/ClassMethod/ArgumentValueResolverToValueResolverRector/ArgumentValueResolverToValueResolverRectorTest.php
rules-tests/Symfony62/Rector/ClassMethod/ArgumentValueResolverToValueResolverRector/Fixture/replace.php.inc
rules-tests/Symfony62/Rector/ClassMethod/ArgumentValueResolverToValueResolverRector/Fixture/replace_none_identical.php.inc
rules-tests/Symfony62/Rector/ClassMethod/ArgumentValueResolverToValueResolverRector/Fixture/skip.php.inc
rules-tests/Symfony62/Rector/ClassMethod/ArgumentValueResolverToValueResolverRector/config/configured_rule.php
rules/Configs/Rector/Closure/ServiceSettersToSettersAutodiscoveryRector.php
rules/Symfony42/Rector/New_/StringToArrayArgumentProcessRector.php
rules/Symfony62/Rector/ClassMethod/ClassMethod/ArgumentValueResolverToValueResolverRector.php
stubs/Symfony/Component/HttpKernel/Controller/ValueResolverInterface.php
tests/Rector/ClassMethod/ArgumentValueResolverToValueResolverRector/config/configured_rule.php

[ArgumentValueResolverToValueResolverRector] Add rule (#289)

---

config/sets/symfony/symfony6/symfony-return-types.php

Ref https://github.com/rectorphp/rector-src/pull/4859

Use array_merge() instead of unpack syntax in symfony config

---

rules-tests/Symfony43/Rector/ClassMethod/EventDispatcherParentConstructRector/Fixture/skip_no_parent.php.inc
rules/Symfony43/Rector/ClassMethod/EventDispatcherParentConstructRector.php

Fixes https://github.com/rectorphp/rector/issues/8159

Fix EventDispatcherParentConstructRector

---

rules/Symfony43/Rector/StmtsAwareInterface/TwigBundleFilesystemLoaderToTwigRector.php

Already covered in rector-src on PR:
- https://github.com/rectorphp/rector-src/pull/4936

Remove dynamic object tweak on TwigBundleFilesystemLoaderToTwigRector

---

rules-tests/CodeQuality/Rector/Class_/MakeCommandLazyRector/Fixture/method_chaining.php.inc
rules-tests/CodeQuality/Rector/Class_/MakeCommandLazyRector/Fixture/method_chaining_with_options.php.inc
rules/CodeQuality/Rector/Class_/MakeCommandLazyRector.php

Adding handling of method chaining for MakeCommandLazyRector

---

rules/CodeQuality/Rector/ClassMethod/ParamTypeFromRouteRequiredRegexRector.php
rules/Symfony34/Rector/ClassMethod/ReplaceSensioRouteAnnotationWithSymfonyRector.php
rules/Symfony63/Rector/Class_/SignalableCommandInterfaceReturnTypeRector.php

Ref https://github.com/rectorphp/rector-src/pull/5091

Move pull StaticTypeMapper from AbstractRector into rules

---

rules-tests/Symfony42/Rector/New_/StringToArrayArgumentProcessRector/Fixture/skip_prepare_stmts.php.inc

Closes https://github.com/rectorphp/rector-symfony/issues/533

Add test fixture for invalid override by StringToArrayArgumentProcessRector

---

rules-tests/Symfony51/Rector/ClassMethod/RouteCollectionBuilderToRoutingConfiguratorRector/Fixture/skip_different_type.php.inc
rules/Symfony51/Rector/ClassMethod/RouteCollectionBuilderToRoutingConfiguratorRector.php

Closes https://github.com/rectorphp/rector-symfony/issues/500

Handle only Kernel in RouteCollectionBuilderToRoutingConfiguratorRector

---

composer.json

This reverts commit 997bee74e102c6cf70bb73e8f59cb6cd3fe44431.

Revert "Temporary use rector-src:dev-rever-doctrine-inflector (#542)"

---

rules-tests/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector/Fixture/security_access_manager.php.inc
rules/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector.php
rules/Configs/ConfigArrayHandler/SecurityAccessDecisionManagerConfigArrayHandler.php
rules/Configs/Enum/SecurityConfigKey.php

- add strategy fixes
- Add accessDecisionManager()

tv strategy

---

rules-tests/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector/Fixture/doctrine_extension.php.inc
rules/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector.php
rules/Configs/ConfigArrayHandler/NestedConfigCallsFactory.php

- add fixture
- kick off
- get nested dbal() calls

tv doctrine oconfig

---

rules-tests/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector/Fixture/doctrine_extension.php.inc
rules/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector.php
rules/Configs/ConfigArrayHandler/NestedConfigCallsFactory.php
rules/Configs/ConfigArrayHandler/SecurityAccessDecisionManagerConfigArrayHandler.php

tv doctrine 2

---

rules-tests/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector/Fixture/doctrine_orm.php.inc
rules/Configs/ConfigArrayHandler/NestedConfigCallsFactory.php
tests/Set/Symfony44/Fixture/event_fixture.php

- add doctrine_orm
- add split

tv doctrine 3

---

rules-tests/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector/Fixture/doctrine_orm_and_dbal.php.inc
rules/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector.php

- add fixture
- keep nested variable separated

tv nested arrays

---

rules-tests/Configs/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/double_route.php.inc
rules-tests/Configs/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture.php.inc
rules-tests/Configs/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture_duplicate.php.inc
rules-tests/Configs/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture_missing_route.php.inc
rules-tests/Configs/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture_with_existing_annotation.php.inc
rules-tests/Configs/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture_with_null_as_default.php.inc
rules-tests/Configs/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/invokable_controller.php.inc
rules-tests/Configs/Rector/ClassMethod/AddRouteAnnotationRector/config/routes.json
rules/Configs/Rector/ClassMethod/AddRouteAnnotationRector.php

Fixes https://github.com/rectorphp/rector/issues/8385
Fixes https://github.com/rectorphp/rector-symfony/issues/554

[Configs] Fix collect routes from Symfony router on AddRouteAnnotationRector

---

composer.json
phpstan.neon
rector.php
rules-tests/Configs/Rector/ClassMethod/AddRouteAnnotationRector/Fixture/fixture_with_existing_annotation.php.inc
rules-tests/Configs/Rector/ClassMethod/AddRouteAnnotationRector/config/configured_rule.php

Fixes https://github.com/rectorphp/rector-symfony/issues/580

[Config] Make use of registerService() method in config

---

.github/workflows/code_analysis.yaml
composer.json

Ref https://github.com/rectorphp/rector-src/pull/5847

Bump class-leak to ^0.2.13

---

rules-tests/CodeQuality/Rector/MethodCall/LiteralGetToRequestClassConstantRector/Fixture/from_kernel_browser.php.inc
rules/CodeQuality/Rector/MethodCall/LiteralGetToRequestClassConstantRector.php
stubs/Symfony/Bundle/FrameworkBundle/KernelBrowser.php
stubs/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php

Fixes https://github.com/rectorphp/rector/issues/8613

[CodeQuality] Add KernelBrowser support on LiteralGetToRequestClassConstantRector

---

config/sets/symfony/symfony50-types.php
rector.php
rules/CodeQuality/NodeFactory/SymfonyClosureFactory.php
rules/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector.php
rules/Configs/ConfigArrayHandler/NestedConfigCallsFactory.php
rules/Configs/Rector/ClassMethod/AddRouteAnnotationRector.php
rules/Symfony64/Rector/Class_/ChangeRouteAttributeFromAnnotationSubnamespaceRector.php
src/Helper/TemplateGuesser.php

Ref https://github.com/rectorphp/rector/issues/8641#issuecomment-2118806416

[PHPStan 1.11] Update config to avoid using TypeCombinator::addNull(), use new UnionType() instead

---

rector.php
rules/Configs/Rector/Closure/ServiceSettersToSettersAutodiscoveryRector.php
rules/Symfony40/Rector/MethodCall/FormIsValidRector.php
rules/Symfony44/Rector/MethodCall/AuthorizationCheckerIsGrantedExtractorRector.php

see https://github.com/rectorphp/rector-src/pull/5924

Enable rectorPreset set

---

docs/rector_rules_overview.md
rules-tests/SwiftMailer/Rector/ClassMethod/SwiftMessageToEmailRector/Fixture/message.php.inc
rules-tests/SwiftMailer/Rector/ClassMethod/SwiftMessageToEmailRector/Fixture/message_id.php.inc
rules-tests/SwiftMailer/Rector/ClassMethod/SwiftMessageToEmailRector/Fixture/symfony_example.php.inc
rules/SwiftMailer/Rector/ClassMethod/SwiftMessageToEmailRector.php
stubs/SwiftMailer/Swift_Message.php
stubs/Symfony/Component/Mime/Email.php
stubs/Symfony/Component/Mime/Header/HeaderInterface.php
stubs/Symfony/Component/Mime/Header/Headers.php
stubs/Symfony/Component/Mime/Message.php

- Adds support for Swift_Message::getId
- Adds support for Swift_Message::addPart
- Fix handling multiple recipients

Adding missing features for Swift_Message > Email

---

rules-tests/Symfony42/Rector/MethodCall/ContainerGetToConstructorInjectionRector/Fixture/constant_as_service_regression.php.inc
rules/Symfony42/Rector/MethodCall/ContainerGetToConstructorInjectionRector.php

Fixes: https://github.com/rectorphp/rector-symfony/issues/598
Proof of error: https://getrector.com/demo/b7387a86-a969-49c2-9ef5-3bf163f6e036

Fix constr fetch resulting in invalid injection

---

config/sets/symfony/symfony62.php
rules-tests/Symfony62/Rector/Class_/SecurityAttributeToIsGrantedAttributeRector/Fixture/simple_security.php.inc
rules-tests/Symfony62/Rector/Class_/SecurityAttributeToIsGrantedAttributeRector/SecurityAttributeToIsGrantedAttributeRectorTest.php
rules-tests/Symfony62/Rector/Class_/SecurityAttributeToIsGrantedAttributeRector/config/configured_rule.php
rules/Symfony62/Rector/Class_/SecurityAttributeToIsGrantedAttributeRector.php

Closes https://github.com/rectorphp/rector-symfony/issues/393

[Symfony 6.2] Add SecurityAttributeToIsGrantedAttributeRector

---

config/sets/symfony/symfony70.php
config/sets/symfony/symfony71.php

* https://github.com/symfony/symfony/blob/7.2/UPGRADE-7.1.md
* https://github.com/symfony/symfony/blob/7.2/UPGRADE-7.0.md

[Symfony 7.0 and 7.1] Extend sets based on upgrade notes

---

rules/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector.php

- added `Symfony\Config\DebugConfig`
- added `Symfony\Config\MakerConfig`

feat: two additional config

---

rules/CodeQuality/Rector/Closure/StringExtensionToConfigBuilderRector.php

- Added `Symfony\Config\NelmioCorsConfig`

feat: add nelmio/cors-bundle config key

---

rules-tests/Configs/Rector/Class_/AutowireAttributeRector/Fixture/multi_args.php.inc
rules-tests/Configs/Rector/Class_/AutowireAttributeRector/Fixture/with_constant.php.inc
rules-tests/Configs/Rector/Class_/AutowireAttributeRector/Source/ParameterName.php
rules-tests/Configs/Rector/Class_/AutowireAttributeRector/Source/configs/app_config.php
rules-tests/Configs/Rector/Class_/AutowireAttributeRector/Source/configs/config_with_constant.php
rules-tests/Configs/Rector/Class_/AutowireAttributeRector/Source/configs/multi_args.php
rules/Configs/NodeAnalyser/ConfigServiceArgumentsResolver.php
rules/Configs/NodeVisitor/CollectServiceArgumentsNodeVisitor.php
rules/Configs/Rector/Class_/AutowireAttributeRector.php
rules/Configs/ValueObject/ServiceArguments.php
src/PhpParser/NamedSimplePhpParser.php

Follow up to https://github.com/rectorphp/rector-symfony/pull/637
Ref https://symfony.com/blog/new-in-symfony-6-1-service-autowiring-attributes

Add args() support to AutowireAttributeRector

---

rules/Symfony61/Rector/Class_/CommandConfigureToAttributeRector.php
rules/Symfony61/Rector/Class_/CommandPropertyToAttributeRector.php
tests/Issues/Issue638/Fixture/name_and_description_order.php.inc
tests/Issues/Issue638/Issue638Test.php
tests/Issues/Issue638/config/configured_rule.php

* https://github.com/rectorphp/rector-symfony/issues/638#issuecomment-2214077706

[Symfony 6.1] Improve CommandPropertyToAttributeRector to work with freshly created AsCommand

---

docs/rector_rules_overview.md
rules-tests/Configs/Rector/Class_/ParameterBagToAutowireAttributeRector/Fixture/keep_parameter_bag_if_used.php.inc
rules-tests/Configs/Rector/Class_/ParameterBagToAutowireAttributeRector/Fixture/some_parameter_bag.php.inc
rules-tests/Configs/Rector/Class_/ParameterBagToAutowireAttributeRector/ParameterBagToAutowireAttributeRectorTest.php
rules-tests/Configs/Rector/Class_/ParameterBagToAutowireAttributeRector/config/configured_rule.php
rules/CodeQuality/Rector/ClassMethod/ResponseReturnTypeControllerActionRector.php
rules/Configs/NodeFactory/AutowiredParamFactory.php
rules/Configs/Rector/Class_/AutowireAttributeRector.php
rules/Configs/Rector/Class_/ParameterBagToAutowireAttributeRector.php

Closes https://github.com/rectorphp/rector-symfony/issues/648

[Config] Add ParameterBagToAutowireAttributeRector

---

rules/CodeQuality/Rector/ClassMethod/ResponseReturnTypeControllerActionRector.php
rules/Symfony30/Rector/ClassMethod/FormTypeGetParentRector.php

Spotted by https://github.com/rectorphp/rector-src/pull/6281

Fix hook node type check to Class_

---

rules-tests/CodeQuality/Rector/ClassMethod/TemplateAnnotationToThisRenderRector/Fixture/class_level_annotation.php.inc
rules/CodeQuality/Rector/ClassMethod/TemplateAnnotationToThisRenderRector.php
rules/Configs/Rector/Class_/ParameterBagToAutowireAttributeRector.php
src/Annotation/AnnotationAnalyzer.php

- **add class-level fixture**
- **Hook to Class_ node only to make easier to read**

Add Class_ annotation support to TemplateAnnotationToThisRenderRector

---

rules-tests/CodeQuality/Rector/Trait_/AddTraitGetterReturnTypeBasedOnSetterRequiredRector/AddTraitGetterReturnTypeBasedOnSetterRequiredRectorTest.php
rules-tests/CodeQuality/Rector/Trait_/AddTraitGetterReturnTypeBasedOnSetterRequiredRector/Fixture/flip_set_first.php.inc
rules-tests/CodeQuality/Rector/Trait_/AddTraitGetterReturnTypeBasedOnSetterRequiredRector/Fixture/skip_already_has_return_type.php.inc
rules-tests/CodeQuality/Rector/Trait_/AddTraitGetterReturnTypeBasedOnSetterRequiredRector/Fixture/some_trait.php.inc
rules-tests/CodeQuality/Rector/Trait_/AddTraitGetterReturnTypeBasedOnSetterRequiredRector/Fixture/with_required_attribute.php.inc
rules-tests/CodeQuality/Rector/Trait_/AddTraitGetterReturnTypeBasedOnSetterRequiredRector/config/configured_rule.php
rules/CodeQuality/Rector/Trait_/AddTraitGetterReturnTypeBasedOnSetterRequiredRector.php

@TomasVotruba here the rule for our project for add getter return type by `@required` in settter in trait.

 [CodeQuality] Add AddTraitGetterReturnTypeBasedOnSetterRequiredRector 

---

rules/Symfony26/Rector/MethodCall/RedirectToRouteRector.php

Fixes https://github.com/rectorphp/rector-symfony/issues/691

[scoped] Fix scoped prefixed UrlGeneratorInterface on RedirectToRouteRector

---

composer.json

as PR on rector-src merged:
- https://github.com/rectorphp/rector-src/pull/6652

Back to require-dev rector-src:dev-main

---

config/sets/symfony/symfony60.php
rules-tests/CodeQuality/Rector/Class_/InlineClassRoutePrefixRector/Fixture/with_existing_name.php.inc
rules-tests/CodeQuality/Rector/Class_/InlineClassRoutePrefixRector/Fixture/with_existing_name2.php.inc
rules/CodeQuality/Rector/Class_/InlineClassRoutePrefixRector.php

Fixes https://github.com/rectorphp/rector-symfony/pull/701

[CodeQuality] Concat name annotation/attribute on InlineClassRoutePrefixRector

---

rules-tests/DependencyInjection/Rector/Class_/CommandGetByTypeToConstructorInjectionRector/CommandGetByTypeToConstructorInjectionRectorTest.php
rules-tests/DependencyInjection/Rector/Class_/GetBySymfonyStringToConstructorInjectionRector/GetBySymfonyStringToConstructorInjectionRectorTest.php

Resolved on rector-src PR:
- https://github.com/rectorphp/rector-src/pull/6858

Clean up #[RunClassInSeparateProcess] tweak

---

config/sets/symfony/symfony3/symfony31.php
config/sets/symfony/symfony3/symfony31/symfony31-yaml.php
src/Set/SetProvider/SymfonySetProvider.php

Ref https://github.com/rectorphp/rector/issues/9107

[config] Split off set to set provider for Symfony 3.1-3.4

---

config/sets/symfony/symfony4/symfony43.php
config/sets/symfony/symfony4/symfony43/symfony43-browser-kit.php
config/sets/symfony/symfony4/symfony43/symfony43-cache.php
config/sets/symfony/symfony4/symfony43/symfony43-event-dispatcher.php
config/sets/symfony/symfony4/symfony43/symfony43-framework-bundle.php
config/sets/symfony/symfony4/symfony43/symfony43-http-foundation.php
config/sets/symfony/symfony4/symfony43/symfony43-http-kernel.php
config/sets/symfony/symfony4/symfony43/symfony43-intl.php
config/sets/symfony/symfony4/symfony43/symfony43-security-core.php
config/sets/symfony/symfony4/symfony43/symfony43-security-http.php
config/sets/symfony/symfony4/symfony43/symfony43-twig-bundle.php
config/sets/symfony/symfony4/symfony43/symfony43-workflow.php
rules/CodeQuality/Rector/ClassMethod/TemplateAnnotationToThisRenderRector.php
rules/Symfony43/Rector/MethodCall/ConvertRenderTemplateShortNotationToBundleSyntaxRector.php
src/Enum/SymfonyClass.php
src/Set/SetProvider/SymfonySetProvider.php
src/TypeAnalyzer/ContainerAwareAnalyzer.php
src/TypeAnalyzer/ControllerAnalyzer.php

Ref https://github.com/rectorphp/rector/issues/9107

[symfony 4.3] split of symfony configs per package

---

config/sets/symfony/symfony3/symfony32.php
config/sets/symfony/symfony3/symfony32/symfony32-dependency-injection.php
config/sets/symfony/symfony3/symfony33.php
config/sets/symfony/symfony3/symfony33/symfony33-console.php
config/sets/symfony/symfony3/symfony33/symfony33-debug.php
config/sets/symfony/symfony3/symfony33/symfony33-dependency-injection.php
config/sets/symfony/symfony3/symfony33/symfony33-framework-bundle.php
config/sets/symfony/symfony3/symfony34.php
config/sets/symfony/symfony3/symfony34/symfony34-dependency-injection.php
config/sets/symfony/symfony3/symfony34/symfony34-sensio-framework-extra-bundle.php
config/sets/symfony/symfony3/symfony34/symfony34-yaml.php
config/sets/symfony/symfony4/symfony42/symfony42-forms.php
config/sets/symfony/symfony4/symfony43/symfony43-framework-bundle.php
config/sets/symfony/symfony4/symfony43/symfony43-twig-bundle.php
config/sets/symfony/symfony4/symfony44/symfony44-security-core.php
rules/Symfony34/Rector/Closure/ContainerGetNameToTypeInTestsRector.php
src/Set/SetProvider/Symfony3SetProvider.php
src/Set/SetProvider/Symfony4SetProvider.php

Ref https://github.com/rectorphp/rector/issues/9107

[config] Split off set to set provider for Symfony 3.2-3.4

---

config/sets/symfony/symfony5/symfony54.php
config/sets/symfony/symfony5/symfony54/symfony54-security-core.php
config/sets/symfony/symfony5/symfony54/symfony54-security-http.php
src/Set/SetProvider/Symfony5SetProvider.php

https://github.com/rectorphp/rector-symfony/pull/739#pullrequestreview-2813914941

Extract to symfony-core and symfony-http on 5.4

---

rules-tests/Symfony73/Rector/Class_/GetFiltersToAsTwigFilterAttributeRector/Fixture/with_first_class_callable_filter.php.inc
rules/Symfony73/Rector/Class_/GetFiltersToAsTwigFilterAttributeRector.php

Cover:
```php
new \Twig\TwigFilter('some_filter', $this->someFilter(...)),
```
Ref https://github.com/rectorphp/rector-symfony/pull/761#pullrequestreview-2827165961

[Symfony73] Handle first class callable on GetFiltersToAsTwigFilterAttributeRector

---

config/sets/symfony/symfony7/symfony73/symfony73-twig-bundle.php
rules-tests/Symfony73/Rector/Class_/GetFunctionsToAsTwigFunctionAttributeRector/Fixture/some_get_functions.php.inc
rules-tests/Symfony73/Rector/Class_/GetFunctionsToAsTwigFunctionAttributeRector/GetFunctionsToAsTwigFunctionAttributeRectorTest.php
rules-tests/Symfony73/Rector/Class_/GetFunctionsToAsTwigFunctionAttributeRector/config/configured_rule.php
rules/Symfony73/GetMethodToAsTwigAttributeTransformer.php
rules/Symfony73/NodeAnalyzer/LocalArrayMethodCallableMatcher.php
rules/Symfony73/NodeRemover/ReturnEmptyArrayMethodRemover.php
rules/Symfony73/Rector/Class_/GetFunctionsToAsTwigFunctionAttributeRector.php
src/Enum/TwigClass.php
stubs/Twig/Attribute/AsTwigFilter.php
stubs/Twig/Attribute/AsTwigFunction.php

Follow up to https://github.com/rectorphp/rector-symfony/pull/761
Ref https://symfony.com/blog/new-in-symfony-7-3-twig-extension-attributes
Covering https://github.com/symfony/symfony/pull/52748
Closes https://github.com/rectorphp/rector-symfony/issues/760

kick off GetFunctionsToAsTwigFunctionAttributeRector

---

config/sets/symfony/symfony7/symfony72.php
config/sets/symfony/symfony7/symfony72/symfony72-http-foundation.php
rules-tests/Symfony72/Rector/StmtsAwareInterface/PushRequestToRequestStackConstructorRector/Fixture/new_request_stack_instance_and_push.php.inc
rules-tests/Symfony72/Rector/StmtsAwareInterface/PushRequestToRequestStackConstructorRector/Fixture/skip_if_already_used.php.inc
rules-tests/Symfony72/Rector/StmtsAwareInterface/PushRequestToRequestStackConstructorRector/Fixture/skip_outside_test_case.php.inc
rules-tests/Symfony72/Rector/StmtsAwareInterface/PushRequestToRequestStackConstructorRector/PushRequestToRequestStackConstructorRectorTest.php
rules-tests/Symfony72/Rector/StmtsAwareInterface/PushRequestToRequestStackConstructorRector/config/configured_rule.php
rules/Symfony72/Rector/StmtsAwareInterface/PushRequestToRequestStackConstructorRector.php
src/Enum/SymfonyClass.php

Closes https://github.com/symfony/symfony/pull/57909/ by @alexander-schranz 
Ref https://symfony.com/blog/new-in-symfony-7-2-misc-improvements-part-2#simpler-requeststack-unit-testing

[symfony 7.2] AddPushRequestToRequestStackConstructorRector

---

rules/CodeQuality/Rector/BinaryOp/ResponseStatusCodeRector.php
rules/CodeQuality/Rector/ClassMethod/ActionSuffixRemoverRector.php
rules/CodeQuality/Rector/Class_/EventListenerToEventSubscriberRector.php
rules/Configs/Rector/ClassMethod/AddRouteAnnotationRector.php
rules/Symfony25/Rector/MethodCall/AddViolationToBuildViolationRector.php
rules/Symfony30/Rector/ClassMethod/GetRequestRector.php
rules/Symfony30/Rector/ClassMethod/RemoveDefaultGetBlockPrefixRector.php
rules/Symfony42/Rector/New_/StringToArrayArgumentProcessRector.php
rules/Symfony43/Rector/MethodCall/ConvertRenderTemplateShortNotationToBundleSyntaxRector.php
rules/Symfony43/Rector/MethodCall/WebTestCaseAssertResponseCodeRector.php
rules/Symfony44/Rector/MethodCall/AuthorizationCheckerIsGrantedExtractorRector.php
rules/Symfony51/Rector/ClassMethod/CommandConstantReturnCodeRector.php
rules/Symfony53/Rector/StaticPropertyFetch/KernelTestCaseContainerPropertyDeprecationRector.php
rules/Symfony61/Rector/Class_/CommandConfigureToAttributeRector.php
rules/Symfony61/Rector/StaticPropertyFetch/ErrorNamesPropertyToConstantRector.php
rules/Twig134/Rector/Return_/SimpleFunctionAndFilterRector.php

Ref PR:
- https://github.com/rectorphp/rector-src/pull/6875

Directly use isName(s) and getName() on rector rules when possible

---

rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/with_override.php.inc
rules/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector.php

[Symfony 7.3] Handle with #[\Override] on InvokableCommandInputAttributeRector

---

rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/name_from_constant.php.inc
rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/with_override.php.inc

Bump to php-parser 5.5.0 and update fixture attributes usage

---

rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/without_configure_method.php.inc
rules/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector.php

[Symfony 7.3] Handle commands without configure method in InvokableCommandInputAttributeRector

---

rules-tests/Symfony73/Rector/Class_/ConstraintOptionsToNamedArgumentsRector/Fixture/nested_constraint.php.inc
rules/Symfony73/Rector/Class_/ConstraintOptionsToNamedArgumentsRector.php

Closes https://github.com/rectorphp/rector-symfony/pull/814
Fixes https://github.com/rectorphp/rector/issues/9258

[Symfony73] Handle nested array on ConstraintOptionsToNamedArgumentsRector

---

config/sets/symfony/symfony6/symfony63.php
config/sets/symfony/symfony6/symfony63/symfony63-web-link.php
src/Set/SetProvider/Symfony6SetProvider.php
tests/Set/Symfony63/Fixture/replace_new_link_parameter_value.php.inc
tests/Set/Symfony63/Symfony63Test.php
tests/Set/Symfony63/config/symfony63.php

See https://github.com/rectorphp/rector-symfony/pull/812 & https://github.com/rectorphp/rector/issues/9256
On hold see: https://github.com/rectorphp/rector-src/pull/7068

[SYMFONY 6.3] replace Link argument values with constants

---

config/sets/symfony/symfony3/symfony32.php
config/sets/symfony/symfony3/symfony32/symfony32-http-foundation.php
src/Set/SetProvider/Symfony3SetProvider.php
tests/Set/Symfony32/Fixture/replace_new_cookie_parameter_value.php.inc
tests/Set/Symfony32/Symfony32Test.php
tests/Set/Symfony32/config/symfony32.php

See: https://github.com/rectorphp/rector/issues/9256
On hold see: https://github.com/rectorphp/rector-src/pull/7068

[SYMFONY 3.2] replace Cookie argument values with constants

---

config/sets/symfony/symfony3/symfony32.php
rector.php
rules-tests/CodeQuality/Rector/ClassMethod/ActionSuffixRemoverRector/Fixture/skip_method_exists_after_suffixed_removed.php.inc
rules/CodeQuality/Rector/ClassMethod/ActionSuffixRemoverRector.php
rules/Symfony73/Rector/Class_/AddVoteArgumentToVoteOnAttributeRector.php
rules/Symfony73/Rector/Class_/ConstraintOptionsToNamedArgumentsRector.php

Cause can't redeclare method error.

[CodeQuality] Skip got duplicated method after suffix removed on ActionSuffixRemoverRector

---

rules-tests/CodeQuality/Rector/MethodCall/ParameterBagTypedGetMethodCallRector/Fixture/filter_var.php.inc
rules-tests/CodeQuality/Rector/MethodCall/ParameterBagTypedGetMethodCallRector/Fixture/skip_no_inner_type.php.inc
rules-tests/CodeQuality/Rector/MethodCall/ParameterBagTypedGetMethodCallRector/Fixture/skip_sole_expr_filter_var.php.inc
rules/CodeQuality/Rector/MethodCall/ParameterBagTypedGetMethodCallRector.php

- **add filter var fixture**
- **add filter_var() support to ParameterBagTypedGetMethodCallRector**

[code-quality] add filter_var() support to ParameterBagTypedGetMethodCallRector

---

rules-tests/Symfony73/Rector/Class_/InvokableCommandInputAttributeRector/Fixture/argument_with_default_value.php.inc
rules/Symfony73/NodeAnalyzer/CommandArgumentsResolver.php
rules/Symfony73/NodeAnalyzer/CommandOptionsResolver.php
rules/Symfony73/NodeFactory/CommandInvokeParamsFactory.php
rules/Symfony73/ValueObject/CommandArgument.php
rules/Symfony73/ValueObject/CommandOption.php

Closes https://github.com/rectorphp/rector/issues/9350

[console] [7.3] Add support for default values in InvokableCommandInputAttributeRector
